import { Groq } from 'groq-sdk';

const getQuery = (category) => `You are the game master for a word-based game which relies on a grid of 30 unique nouns or proper nouns to be played. The players of your game need a new list of nouns related to the category '${category}'.

All nouns/proper nouns must relate to the category, but should be distinct from each other. The list of nouns must be returned in the format of the JSON example provided, which contains an array of thirty items.

Format (array must contain 30 items):
""""
{
  "words": [
    "Example Noun", 
    "Example Noun", 
    "Example Proper Noun", 
    "Example Noun",
    ...
    ]
}
""""`;

let words = {};

words['Standard'] = [
  'People',
  'History',
  'Way',
  'Art',
  'World',
  'Information',
  'Map',
  'Two',
  'Family',
  'Government',
  'Health',
  'System',
  'Computer',
  'Meat',
  'Year',
  'Thanks',
  'Music',
  'Person',
  'Reading',
  'Method',
  'Data',
  'Food',
  'Understanding',
  'Theory',
  'Law',
  'Bird',
  'Literature',
  'Problem',
  'Software',
  'Control',
  'Knowledge',
  'Power',
  'Ability',
  'Economics',
  'Love',
  'Internet',
  'Television',
  'Science',
  'Library',
  'Nature',
  'Fact',
  'Product',
  'Idea',
  'Temperature',
  'Investment',
  'Area',
  'Society',
  'Activity',
  'Story',
  'Industry',
  'Media',
  'Thing',
  'Oven',
  'Community',
  'Definition',
  'Safety',
  'Quality',
  'Development',
  'Language',
  'Management',
  'Player',
  'Variety',
  'Video',
  'Week',
  'Security',
  'Country',
  'Exam',
  'Movie',
  'Organization',
  'Equipment',
  'Physics',
  'Analysis',
  'Policy',
  'Series',
  'Thought',
  'Basis',
  'Boyfriend',
  'Direction',
  'Strategy',
  'Technology',
  'Army',
  'Camera',
  'Freedom',
  'Paper',
  'Environment',
  'Child',
  'Instance',
  'Month',
  'Truth',
  'Marketing',
  'University',
  'Writing',
  'Article',
  'Department',
  'Difference',
  'Goal',
  'News',
  'Audience',
  'Fishing',
  'Growth',
  'Income',
  'Marriage',
  'User',
  'Combination',
  'Failure',
  'Meaning',
  'Medicine',
  'Philosophy',
  'Teacher',
  'Communication',
  'Night',
  'Chemistry',
  'Disease',
  'Disk',
  'Energy',
  'Nation',
  'Road',
  'Role',
  'Soup',
  'Advertising',
  'Location',
  'Success',
  'Addition',
  'Apartment',
  'Education',
  'Math',
  'Moment',
  'Painting',
  'Politics',
  'Attention',
  'Decision',
  'Event',
  'Property',
  'Shopping',
  'Student',
  'Wood',
  'Competition',
  'Distribution',
  'Entertainment',
  'Office',
  'Population',
  'President',
  'Unit',
  'Category',
  'Cigarette',
  'Context',
  'Introduction',
  'Opportunity',
  'Performance',
  'Driver',
  'Flight',
  'Length',
  'Magazine',
  'Newspaper',
  'Relationship',
  'Teaching',
  'Cell',
  'Dealer',
  'Finding',
  'Lake',
  'Member',
  'Message',
  'Phone',
  'Scene',
  'Appearance',
  'Association',
  'Concept',
  'Customer',
  'Death',
  'Discussion',
  'Housing',
  'Inflation',
  'Insurance',
  'Mood',
  'Woman',
  'Advice',
  'Blood',
  'Effort',
  'Expression',
  'Importance',
  'Opinion',
  'Payment',
  'Reality',
  'Responsibility',
  'Situation',
  'Skill',
  'Statement',
  'Wealth',
  'Application',
  'City',
  'County',
  'Depth',
  'Estate',
  'Foundation',
  'Grandmother',
  'Heart',
  'Perspective',
  'Photo',
  'Recipe',
  'Studio',
  'Topic',
  'Collection',
  'Depression',
  'Imagination',
  'Passion',
  'Percentage',
  'Resource',
  'Setting',
  'Ad',
  'Agency',
  'College',
  'Connection',
  'Criticism',
  'Debt',
  'Description',
  'Memory',
  'Patience',
  'Secretary',
  'Solution',
  'Administration',
  'Aspect',
  'Attitude',
  'Director',
  'Personality',
  'Psychology',
  'Recommendation',
  'Response',
  'Selection',
  'Storage',
  'Version',
  'Alcohol',
  'Argument',
  'Complaint',
  'Contract',
  'Emphasis',
  'Highway',
  'Loss',
  'Membership',
  'Possession',
  'Preparation',
  'Steak',
  'Union',
  'Agreement',
  'Cancer',
  'Currency',
  'Employment',
  'Engineering',
  'Entry',
  'Interaction',
  'Mixture',
  'Preference',
  'Region',
  'Republic',
  'Tradition',
  'Virus',
  'Actor',
  'Classroom',
  'Delivery',
  'Device',
  'Difficulty',
  'Drama',
  'Election',
  'Engine',
  'Football',
  'Guidance',
  'Hotel',
  'Owner',
  'Priority',
  'Protection',
  'Suggestion',
  'Tension',
  'Variation',
  'Anxiety',
  'Atmosphere',
  'Awareness',
  'Bath',
  'Bread',
  'Candidate',
  'Climate',
  'Comparison',
  'Confusion',
  'Construction',
  'Elevator',
  'Emotion',
  'Employee',
  'Employer',
  'Guest',
  'Height',
  'Leadership',
  'Mall',
  'Manager',
  'Operation',
  'Recording',
  'Sample',
  'Transportation',
  'Charity',
  'Cousin',
  'Disaster',
  'Editor',
  'Efficiency',
  'Excitement',
  'Extent',
  'Feedback',
  'Guitar',
  'Homework',
  'Leader',
  'Mom',
  'Outcome',
  'Permission',
  'Presentation',
  'Promotion',
  'Reflection',
  'Refrigerator',
  'Resolution',
  'Revenue',
  'Session',
  'Singer',
  'Tennis',
  'Basket',
  'Bonus',
  'Cabinet',
  'Childhood',
  'Church',
  'Clothes',
  'Coffee',
  'Dinner',
  'Drawing',
  'Hair',
  'Hearing',
  'Initiative',
  'Judgment',
  'Lab',
  'Measurement',
  'Mode',
  'Mud',
  'Orange',
  'Poetry',
  'Police',
  'Possibility',
  'Procedure',
  'Queen',
  'Ratio',
  'Relation',
  'Restaurant',
  'Satisfaction',
  'Sector',
  'Signature',
  'Significance',
  'Song',
  'Tooth',
  'Town',
  'Vehicle',
  'Volume',
  'Wife',
  'Accident',
  'Airport',
  'Appointment',
  'Arrival',
  'Assumption',
  'Baseball',
  'Chapter',
  'Committee',
  'Conversation',
  'Database',
  'Enthusiasm',
  'Error',
  'Explanation',
  'Farmer',
  'Gate',
  'Girl',
  'Hall',
  'Historian',
  'Hospital',
  'Injury',
  'Instruction',
  'Maintenance',
  'Manufacturer',
  'Meal',
  'Perception',
  'Pie',
  'Poem',
  'Presence',
  'Proposal',
  'Reception',
  'Replacement',
  'Revolution',
  'River',
  'Son',
  'Speech',
  'Tea',
  'Village',
  'Warning',
  'Winner',
  'Worker',
  'Writer',
  'Assistance',
  'Breath',
  'Buyer',
  'Chest',
  'Chocolate',
  'Conclusion',
  'Contribution',
  'Cookie',
  'Courage',
  'Dad',
  'Desk',
  'Drawer',
  'Establishment',
  'Examination',
  'Garbage',
  'Grocery',
  'Honey',
  'Impression',
  'Improvement',
  'Independence',
  'Insect',
  'Inspection',
  'Inspector',
  'King',
  'Ladder',
  'Menu',
  'Penalty',
  'Piano',
  'Potato',
  'Profession',
  'Professor',
  'Quantity',
  'Reaction',
  'Requirement',
  'Salad',
  'Sister',
  'Supermarket',
  'Tongue',
  'Weakness',
  'Wedding',
  'Affair',
  'Ambition',
  'Analyst',
  'Apple',
  'Assignment',
  'Assistant',
  'Bathroom',
  'Bedroom',
  'Beer',
  'Birthday',
  'Celebration',
  'Championship',
  'Cheek',
  'Client',
  'Consequence',
  'Departure',
  'Diamond',
  'Dirt',
  'Ear',
  'Fortune',
  'Friendship',
  'Funeral',
  'Gene',
  'Girlfriend',
  'Hat',
  'Indication',
  'Intention',
  'Lady',
  'Midnight',
  'Negotiation',
  'Obligation',
  'Passenger',
  'Pizza',
  'Platform',
  'Poet',
  'Pollution',
  'Recognition',
  'Reputation',
  'Shirt',
  'Sir',
  'Speaker',
  'Stranger',
  'Surgery',
  'Sympathy',
  'Tale',
  'Throat',
  'Trainer',
  'Uncle',
  'Youth',
  'Time',
  'Work',
  'Film',
  'Water',
  'Money',
  'Example',
  'While',
  'Business',
  'Study',
  'Game',
  'Life',
  'Form',
  'Air',
  'Day',
  'Place',
  'Number',
  'Part',
  'Field',
  'Fish',
  'Back',
  'Process',
  'Heat',
  'Hand',
  'Experience',
  'Job',
  'Book',
  'End',
  'Point',
  'Type',
  'Home',
  'Economy',
  'Value',
  'Body',
  'Market',
  'Guide',
  'Interest',
  'State',
  'Radio',
  'Course',
  'Company',
  'Price',
  'Size',
  'Card',
  'List',
  'Mind',
  'Trade',
  'Line',
  'Care',
  'Group',
  'Risk',
  'Word',
  'Fat',
  'Force',
  'Key',
  'Light',
  'Training',
  'Name',
  'School',
  'Top',
  'Amount',
  'Level',
  'Order',
  'Practice',
  'Research',
  'Sense',
  'Service',
  'Piece',
  'Web',
  'Boss',
  'Sport',
  'Fun',
  'House',
  'Page',
  'Term',
  'Test',
  'Answer',
  'Sound',
  'Focus',
  'Matter',
  'Kind',
  'Soil',
  'Board',
  'Oil',
  'Picture',
  'Access',
  'Garden',
  'Range',
  'Rate',
  'Reason',
  'Future',
  'Site',
  'Demand',
  'Exercise',
  'Image',
  'Case',
  'Cause',
  'Coast',
  'Action',
  'Age',
  'Bad',
  'Boat',
  'Record',
  'Result',
  'Section',
  'Building',
  'Mouse',
  'Cash',
  'Class',
  'Nothing',
  'Period',
  'Plan',
  'Store',
  'Tax',
  'Side',
  'Subject',
  'Space',
  'Rule',
  'Stock',
  'Weather',
  'Chance',
  'Figure',
  'Man',
  'Model',
  'Source',
  'Beginning',
  'Earth',
  'Program',
  'Chicken',
  'Design',
  'Feature',
  'Head',
  'Material',
  'Purpose',
  'Question',
  'Rock',
  'Salt',
  'Act',
  'Birth',
  'Car',
  'Dog',
  'Object',
  'Scale',
  'Sun',
  'Note',
  'Profit',
  'Rent',
  'Speed',
  'Style',
  'War',
  'Bank',
  'Craft',
  'Half',
  'Inside',
  'Outside',
  'Standard',
  'Bus',
  'Exchange',
  'Eye',
  'Fire',
  'Position',
  'Pressure',
  'Stress',
  'Advantage',
  'Benefit',
  'Box',
  'Frame',
  'Issue',
  'Step',
  'Cycle',
  'Face',
  'Item',
  'Metal',
  'Paint',
  'Review',
  'Room',
  'Screen',
  'Structure',
  'View',
  'Account',
  'Ball',
  'Discipline',
  'Medium',
  'Share',
  'Balance',
  'Bit',
  'Black',
  'Bottom',
  'Choice',
  'Gift',
  'Impact',
  'Machine',
  'Shape',
  'Tool',
  'Wind',
  'Address',
  'Average',
  'Career',
  'Culture',
  'Morning',
  'Pot',
  'Sign',
  'Table',
  'Task',
  'Condition',
  'Contact',
  'Credit',
  'Egg',
  'Hope',
  'Ice',
  'Network',
  'North',
  'Square',
  'Attempt',
  'Date',
  'Effect',
  'Link',
  'Post',
  'Star',
  'Voice',
  'Capital',
  'Challenge',
  'Friend',
  'Self',
  'Shot',
  'Brush',
  'Couple',
  'Debate',
  'Exit',
  'Front',
  'Function',
  'Lack',
  'Living',
  'Plant',
  'Plastic',
  'Spot',
  'Summer',
  'Taste',
  'Theme',
  'Track',
  'Wing',
  'Brain',
  'Button',
  'Click',
  'Desire',
  'Foot',
  'Gas',
  'Influence',
  'Notice',
  'Rain',
  'Wall',
  'Base',
  'Damage',
  'Distance',
  'Feeling',
  'Pair',
  'Savings',
  'Staff',
  'Sugar',
  'Target',
  'Text',
  'Animal',
  'Author',
  'Budget',
  'Discount',
  'File',
  'Ground',
  'Lesson',
  'Minute',
  'Officer',
  'Phase',
  'Reference',
  'Register',
  'Sky',
  'Stage',
  'Stick',
  'Title',
  'Trouble',
  'Bowl',
  'Bridge',
  'Campaign',
  'Character',
  'Club',
  'Edge',
  'Evidence',
  'Fan',
  'Letter',
  'Lock',
  'Maximum',
  'Novel',
  'Option',
  'Pack',
  'Park',
  'Plenty',
  'Quarter',
  'Skin',
  'Sort',
  'Weight',
  'Baby',
  'Background',
  'Carry',
  'Dish',
  'Factor',
  'Fruit',
  'Glass',
  'Joint',
  'Master',
  'Muscle',
  'Red',
  'Strength',
  'Traffic',
  'Trip',
  'Vegetable',
  'Appeal',
  'Chart',
  'Gear',
  'Ideal',
  'Kitchen',
  'Land',
  'Log',
  'Mother',
  'Net',
  'Party',
  'Principle',
  'Relative',
  'Sale',
  'Season',
  'Signal',
  'Spirit',
  'Street',
  'Tree',
  'Wave',
  'Belt',
  'Bench',
  'Commission',
  'Copy',
  'Drop',
  'Minimum',
  'Path',
  'Progress',
  'Project',
  'Sea',
  'South',
  'Status',
  'Stuff',
  'Ticket',
  'Tour',
  'Angle',
  'Blue',
  'Breakfast',
  'Confidence',
  'Daughter',
  'Degree',
  'Doctor',
  'Dot',
  'Dream',
  'Duty',
  'Essay',
  'Father',
  'Fee',
  'Finance',
  'Hour',
  'Juice',
  'Limit',
  'Luck',
  'Milk',
  'Mouth',
  'Peace',
  'Pipe',
  'Seat',
  'Stable',
  'Storm',
  'Substance',
  'Team',
  'Trick',
  'Afternoon',
  'Bat',
  'Beach',
  'Blank',
  'Catch',
  'Chain',
  'Consideration',
  'Cream',
  'Crew',
  'Detail',
  'Gold',
  'Interview',
  'Kid',
  'Mark',
  'Match',
  'Mission',
  'Pain',
  'Pleasure',
  'Score',
  'Screw',
  'Sex',
  'Shop',
  'Shower',
  'Suit',
  'Tone',
  'Window',
  'Agent',
  'Band',
  'Block',
  'Bone',
  'Calendar',
  'Cap',
  'Coat',
  'Contest',
  'Corner',
  'Court',
  'Cup',
  'District',
  'Door',
  'East',
  'Finger',
  'Garage',
  'Guarantee',
  'Hole',
  'Hook',
  'Implement',
  'Layer',
  'Lecture',
  'Lie',
  'Manner',
  'Meeting',
  'Nose',
  'Parking',
  'Partner',
  'Profile',
  'Respect',
  'Rice',
  'Routine',
  'Schedule',
  'Swimming',
  'Telephone',
  'Tip',
  'Winter',
  'Airline',
  'Bag',
  'Battle',
  'Bed',
  'Bill',
  'Bother',
  'Cake',
  'Code',
  'Curve',
  'Designer',
  'Dimension',
  'Dress',
  'Ease',
  'Emergency',
  'Evening',
  'Extension',
  'Farm',
  'Fight',
  'Gap',
  'Grade',
  'Holiday',
  'Horror',
  'Horse',
  'Host',
  'Husband',
  'Loan',
  'Mistake',
  'Mountain',
  'Nail',
  'Noise',
  'Occasion',
  'Package',
  'Patient',
  'Pause',
  'Phrase',
  'Proof',
  'Race',
  'Relief',
  'Sand',
  'Sentence',
  'Shoulder',
  'Smoke',
  'Stomach',
  'String',
  'Tourist',
  'Towel',
  'Vacation',
  'West',
  'Wheel',
  'Wine',
  'Arm',
  'Aside',
  'Associate',
  'Bet',
  'Blow',
  'Border',
  'Branch',
  'Breast',
  'Brother',
  'Buddy',
  'Bunch',
  'Chip',
  'Coach',
  'Cross',
  'Document',
  'Draft',
  'Dust',
  'Expert',
  'Floor',
  'God',
  'Golf',
  'Habit',
  'Iron',
  'Judge',
  'Knife',
  'Landscape',
  'League',
  'Mail',
  'Mess',
  'Native',
  'Opening',
  'Parent',
  'Pattern',
  'Pin',
  'Pool',
  'Pound',
  'Request',
  'Salary',
  'Shame',
  'Shelter',
  'Shoe',
  'Silver',
  'Tackle',
  'Tank',
  'Trust',
  'Assist',
  'Bake',
  'Bar',
  'Bell',
  'Bike',
  'Blame',
  'Boy',
  'Brick',
  'Chair',
  'Closet',
  'Clue',
  'Collar',
  'Comment',
  'Conference',
  'Devil',
  'Diet',
  'Fear',
  'Fuel',
  'Glove',
  'Jacket',
  'Lunch',
  'Monitor',
  'Mortgage',
  'Nurse',
  'Pace',
  'Panic',
  'Peak',
  'Plane',
  'Reward',
  'Row',
  'Sandwich',
  'Shock',
  'Spite',
  'Spray',
  'Surprise',
  'Till',
  'Transition',
  'Weekend',
  'Welcome',
  'Yard',
  'Alarm',
  'Bend',
  'Bicycle',
  'Bite',
  'Blind',
  'Bottle',
  'Cable',
  'Candle',
  'Clerk',
  'Cloud',
  'Concert',
  'Counter',
  'Flower',
  'Grandfather',
  'Harm',
  'Knee',
  'Lawyer',
  'Leather',
  'Load',
  'Mirror',
  'Neck',
  'Pension',
  'Plate',
  'Purple',
  'Ruin',
  'Ship',
  'Skirt',
  'Slice',
  'Snow',
  'Specialist',
  'Stroke',
  'Switch',
  'Trash',
  'Tune',
  'Zone',
  'Anger',
  'Award',
  'Bid',
  'Bitter',
  'Boot',
  'Bug',
  'Camp',
  'Candy',
  'Carpet',
  'Cat',
  'Champion',
  'Channel',
  'Clock',
  'Comfort',
  'Cow',
  'Crack',
  'Engineer',
  'Entrance',
  'Fault',
  'Grass',
  'Guy',
  'Hell',
  'Highlight',
  'Incident',
  'Island',
  'Joke',
  'Jury',
  'Leg',
  'Lip',
  'Mate',
  'Motor',
  'Nerve',
  'Passage',
  'Pen',
  'Pride',
  'Priest',
  'Prize',
  'Promise',
  'Resident',
  'Resort',
  'Ring',
  'Roof',
  'Rope',
  'Sail',
  'Scheme',
  'Script',
  'Sock',
  'Station',
  'Toe',
  'Tower',
  'Truck',
  'Witness',
  //'A',
  //'You',
  'It',
  'Can',
  'Will',
  //'If',
  'One',
  'Many',
  'Most',
  'Other',
  'Use',
  'Make',
  'Good',
  'Look',
  'Help',
  'Go',
  'Great',
  'Being',
  'Few',
  'Might',
  'Still',
  'Public',
  'Read',
  'Keep',
  'Start',
  'Give',
  'Human',
  'Local',
  'General',
  'She',
  'Specific',
  'Long',
  'Play',
  'Feel',
  'High',
  'Tonight',
  'Put',
  'Common',
  'Set',
  'Change',
  'Simple',
  'Past',
  'Big',
  'Possible',
  'Particular',
  'Today',
  'Major',
  'Personal',
  'Current',
  'National',
  'Cut',
  'Natural',
  'Physical',
  'Show',
  'Try',
  'Check',
  'Second',
  'Call',
  'Move',
  'Pay',
  'Let',
  'Increase',
  'Single',
  'Individual',
  'Turn',
  'Ask',
  'Buy',
  'Guard',
  'Hold',
  'Main',
  'Offer',
  'Potential',
  'Professional',
  'International',
  'Travel',
  'Cook',
  'Alternative',
  'Following',
  'Special',
  'Working',
  'Whole',
  'Dance',
  'Excuse',
  'Cold',
  'Commercial',
  'Low',
  'Purchase',
  'Deal',
  'Primary',
  'Worth',
  'Fall',
  'Necessary',
  'Positive',
  'Produce',
  'Search',
  'Present',
  'Spend',
  'Talk',
  'Creative',
  'Tell',
  'Cost',
  'Drive',
  'Green',
  'Support',
  'Glad',
  'Remove',
  'Return',
  'Run',
  'Complex',
  'Due',
  'Effective',
  'Middle',
  'Regular',
  'Reserve',
  'Independent',
  'Leave',
  'Original',
  'Reach',
  'Rest',
  'Serve',
  'Watch',
  'Beautiful',
  'Charge',
  'Active',
  'Break',
  'Negative',
  'Safe',
  'Stay',
  'Visit',
  'Visual',
  'Affect',
  'Cover',
  'Report',
  'Rise',
  'Walk',
  'White',
  'Beyond',
  'Junior',
  'Pick',
  'Unique',
  'Anything',
  'Classic',
  'Final',
  'Lift',
  'Mix',
  'Private',
  'Stop',
  'Teach',
  'Western',
  'Concern',
  'Familiar',
  'Fly',
  'Official',
  'Broad',
  'Comfortable',
  'Gain',
  'Maybe',
  'Rich',
  'Save',
  'Stand',
  'Young',
  'Fail',
  'Heavy',
  'Hello',
  'Lead',
  'Listen',
  'Valuable',
  'Worry',
  'Handle',
  'Leading',
  'Meet',
  'Release',
  'Sell',
  'Finish',
  'Normal',
  'Press',
  'Ride',
  'Secret',
  'Spread',
  'Spring',
  'Tough',
  'Wait',
  'Brown',
  'Deep',
  'Display',
  'Flow',
  'Hit',
  'Objective',
  'Shoot',
  'Touch',
  'Cancel',
  'Chemical',
  'Cry',
  'Dump',
  'Extreme',
  'Push',
  'Conflict',
  'Eat',
  'Fill',
  'Formal',
  'Jump',
  'Kick',
  'Opposite',
  'Pass',
  'Pitch',
  'Remote',
  'Total',
  'Treat',
  'Vast',
  'Abuse',
  'Beat',
  'Burn',
  'Deposit',
  'Print',
  'Raise',
  'Sleep',
  'Somewhere',
  'Advance',
  'Anywhere',
  'Consist',
  'Dark',
  'Double',
  'Draw',
  'Equal',
  'Fix',
  'Hire',
  'Internal',
  'Join',
  'Kill',
  'Sensitive',
  'Tap',
  'Win',
  'Attack',
  'Claim',
  'Constant',
  'Drag',
  'Drink',
  'Guess',
  'Minor',
  'Pull',
  'Raw',
  'Soft',
  'Solid',
  'Wear',
  'Weird',
  'Wonder',
  'Annual',
  'Count',
  'Dead',
  'Doubt',
  'Feed',
  'Forever',
  'Impress',
  'Nobody',
  'Repeat',
  'Round',
  'Sing',
  'Slide',
  'Strip',
  'Whereas',
  'Wish',
  'Combine',
  'Command',
  'Dig',
  'Divide',
  'Equivalent',
  'Hang',
  'Hunt',
  'Initial',
  'March',
  'Mention',
  'Smell',
  'Spiritual',
  'Survey',
  'Tie',
  'Adult',
  'Brief',
  'Crazy',
  'Escape',
  'Gather',
  'Hate',
  'Prior',
  'Repair',
  'Rough',
  'Sad',
  'Scratch',
  'Sick',
  'Strike',
  'Employ',
  'External',
  'Hurt',
  'Illegal',
  'Laugh',
  'Lay',
  'Mobile',
  'Nasty',
  'Ordinary',
  'Respond',
  'Royal',
  'Senior',
  'Split',
  'Strain',
  'Struggle',
  'Swim',
  'Train',
  'Upper',
  'Wash',
  'Yellow',
  'Convert',
  'Crash',
  'Dependent',
  'Fold',
  'Funny',
  'Grab',
  'Hide',
  'Miss',
  'Permit',
  'Quote',
  'Recover',
  'Resolve',
  'Roll',
  'Sink',
  'Slip',
  'Spare',
  'Suspect',
  'Sweet',
  'Swing',
  'Twist',
  'Upstairs',
  'Usual',
  'Abroad',
  'Brave',
  'Calm',
  'Concentrate',
  'Estimate',
  'Grand',
  'Male',
  'Mine',
  'Prompt',
  'Quiet',
  'Refuse',
  'Regret',
  'Reveal',
  'Rush',
  'Shake',
  'Shift',
  'Shine',
  'Steal',
  'Suck',
  'Surround',
  'Anybody',
  'Bear',
  'Brilliant',
  'Dare',
  'Dear',
  'Delay',
  'Drunk'
];

words['Salesforce'] = [
  'Account',
  'Activate',
  'Admin',
  'Agentforce',
  'Analyze',
  'Apex Class',
  'API Name',
  'API Version',
  'APIs',
  'App Builder',
  'App Launcher',
  'AppExchange',
  'Approval Process',
  'Architect',
  'Archive',
  'Article',
  'Asset',
  'Assignment Rule',
  'AssignmentDebug',
  'Asynchronous',
  'Aura Component',
  'Auto-Launched Flow',
  'Automate',
  'Backup',
  'Batch',
  'Big Object',
  'Build',
  'Business Analyst',
  'Call',
  'Format',
  'Rich Text',
  'Campaign',
  'Cancel',
  'Case',
  'Certification',
  'Change Data Capture',
  'Change Log',
  'Change Set',
  'Chat',
  'Chatter',
  'Classic',
  'Clean',
  'Clone',
  'Close',
  'Code Builder',
  'Code Coverage',
  'Collaborate',
  'Comment',
  'Community',
  'Community User',
  'Compact Layout',
  'Configure',
  'Connected App',
  'Console App',
  'Contact',
  'Contract',
  'Copado',
  'Create',
  'CRM Analytics',
  'Currency',
  'Custom Label',
  'Custom Metadata',
  'Custom Setting',
  'Customize',
  'Dashboard',
  'Data Cloud',
  'Data Import Wizard',
  'Data Loader',
  'Data Model',
  'Delegation',
  'Delete',
  'Deploy',
  'Developer',
  'Developer Console',
  'DevOps Center',
  'Draft',
  'Duplicate',
  'Duplicate Rules',
  'Dynamic Forms',
  'Edit',
  'Edition',
  'Einstein',
  'Email Template',
  'Email-to-Case',
  'Embed',
  'Encryption',
  'Enhance',
  'Enhanced Domains',
  'Enhanced MFA',
  'Entitlement',
  'Event',
  'Experience Builder',
  'Experience Cloud',
  'Export',
  'External Object',
  'External Services',
  'Favorite',
  'Feed Item',
  'Field',
  'Field-Level Security',
  'File',
  'Filter',
  'Flow',
  'Flow Builder',
  'Flow Orchestration',
  'Folder',
  'Follow',
  'Forecast',
  'Formula',
  'Fusekit',
  'Future Method',
  'Git',
  'Global Actions',
  'Global Search',
  'Governor Limits',
  'Guest User',
  'Health Cloud',
  'Heroku',
  'History Tracking',
  'HTML',
  'Huddles',
  'Hyperforce',
  'IC',
  'Identity Provider',
  'Import',
  'Informatica',
  'Install',
  'Integration User',
  'Invoice',
  'Jetstream',
  'Joined Report',
  'Junction Object',
  'Kanban',
  'Knowledge',
  'Landing Page',
  'Lead',
  'Lead Conversion',
  'License',
  'Lightning',
  'Lightning App',
  'Lightning Record Page',
  'Lightning Web Component',
  'Link',
  'List View',
  'Live Agent',
  'Lock',
  'Log',
  'Login',
  'Login IP Ranges',
  'Logout',
  'Lookup',
  'Macros',
  'Managed Package',
  'Manufacturing Cloud',
  'Marketing Cloud',
  'Master-Detail',
  'Matching Rules',
  'Matrix Report',
  'Metadata',
  'Migrate',
  'Milestone',
  'Monitor',
  'Mulesoft',
  'Multi-factor Authentication',
  'Multi-Select Picklist',
  'My Domain',
  'Named Credential',
  'Navigate',
  'Notification',
  'Number',
  'Object',
  'Omni-Channel',
  'OmniStudio',
  'Opportunity',
  'Optimize',
  'Order',
  'Org',
  'Org-Wide Defaults',
  'Page Layout',
  'Passwordless Login',
  'Pause',
  'Permission Set',
  'Permission Set Group',
  'Personalize',
  'Picklist',
  'Pipeline',
  'Platform Event',
  'Preview',
  'Price Book',
  'Prioritize',
  'Private Connect',
  'Process Automation User',
  'Process Builder',
  'Product',
  'Product Owner',
  'Production',
  'Profile',
  'Prompt Builder',
  'Prompt Templates',
  'Prospect',
  'Provision',
  'Public Group',
  'Public Site',
  'QA',
  'Queue',
  'Queueable Apex',
  'Quick Actions',
  'Quip',
  'Quote',
  'Quote Line Item',
  'Rebuild',
  'Record',
  'Record ID',
  'Record Type',
  'Record-Triggered Flow',
  'Recursion',
  'Refresh',
  'Regional Data Storage',
  'Relationships',
  'Release Management',
  'Report',
  'Report Type',
  'Reset',
  'REST Endpoint',
  'Revenue Lifecycle Management',
  'Review',
  'Role',
  'Role Hierarchy',
  'Roll-Up Summary',
  'Sales Cloud',
  'Sales Path',
  'Salesforce–Slack Automation',
  'Sandbox',
  'Sandbox Refresh',
  'Save',
  'Schedule',
  'Scheduled Flow',
  'Schema Builder',
  'Scratch Org',
  'Screen Flow',
  'Security Center',
  'Seeding',
  'Service Cloud',
  'Setup',
  'SF CLI',
  'Share',
  'Sharing',
  'Sharing Rule',
  'Shield',
  'Slack',
  'SOQL',
  'Sort',
  'SOSL',
  'Source Control',
  'Spiff',
  'SSO',
  'Staging',
  'Static Resource',
  'Subscribe',
  'Summary Report',
  'Superbadge',
  'Sync',
  'Tab',
  'Tableau',
  'Task',
  'Territory',
  'Test',
  'Test Class',
  'Text',
  'Text Area',
  'Trailhead',
  'Transform',
  'Translation',
  'Trigger',
  'UAT',
  'Unified Customer Profile',
  'Unit Test',
  'Unmanaged Package',
  'Update',
  'Upload',
  'Upsert',
  'User',
  'Utility Bar',
  'Validate',
  'Validation',
  'Visitor',
  'Visualforce',
  'Vlocity',
  'VS Code',
  'Web-to-Case',
  'Web-to-Lead',
  'Webhook',
  'Workbench',
  'Workflow Rule',
  'XML'
];

words['Official'] = [
  'Ace',
  'Africa',
  'Agent',
  'Aid',
  'Air',
  'Aladdin',
  'Alaska',
  'Alien',
  'Alps',
  'Amazon',
  'Ambulance',
  'America',
  'Anchor',
  'Angel',
  'Ant',
  'Antarctica',
  'Anteater',
  'Anthem',
  'Apple',
  'Apron',
  'Aqueduct',
  'Arena',
  'Arm',
  'Armor',
  'Armstrong',
  'Army',
  'Ash',
  'Astronaut',
  'Atlantis',
  'Attic',
  'Australia',
  'Avalanche',
  'Axe',
  'Aztec',
  'Baby',
  'Back',
  'Bacon',
  'Balcony',
  'Ball',
  'Ballet',
  'Balloon',
  'Banana',
  'Band',
  'Bank',
  'Bar',
  'Barbecue',
  'Bark',
  'Base',
  'Bass',
  'Bat',
  'Bath',
  'Battery',
  'Battle',
  'Battleship',
  'Bay',
  'Beach',
  'Beam',
  'Bean',
  'Bear',
  'Beard',
  'Beat',
  'Bed',
  'Bee',
  'Beer',
  'Beijing',
  'Bell',
  'Belt',
  'Bench',
  'Berlin',
  'Bermuda',
  'Berry',
  'Bicycle',
  'Big Bang',
  'Big Ben',
  'Bikini',
  'Bill',
  'Birch',
  'Birth',
  'Biscuit',
  'Black Hole',
  'Blackberry',
  'Blacksmith',
  'Blade',
  'Blind',
  'Blizzard',
  'Block',
  'Blues',
  'Board',
  'Boil',
  'Bolt',
  'Bomb',
  'Bond',
  'Bonsai',
  'Book',
  'Boom',
  'Boomerang',
  'Boot',
  'Boss',
  'Bottle',
  'Bow',
  'Bowl',
  'Bowler',
  'Box',
  'Boxer',
  'Brain',
  'Brass',
  'Brazil',
  'Bread',
  'Break',
  'Brick',
  'Bride',
  'Bridge',
  'Brother',
  'Brush',
  'Bubble',
  'Buck',
  'Bucket',
  'Buffalo',
  'Bug',
  'Bugle',
  'Bulb',
  'Bunch',
  'Bunk',
  'Butter',
  'Butterfly',
  'Button',
  'Cable',
  'Caesar',
  'Cake',
  'Calf',
  'Camel',
  'Camp',
  'Canada',
  'Candle',
  'Cane',
  'Cap',
  'Capital',
  'Captain',
  'Car',
  'Card',
  'Carrot',
  'Casino',
  'Cast',
  'Castle',
  'Cat',
  'Caterpillar',
  'Caution',
  'Cave',
  'Cell',
  'Centaur',
  'Center',
  'Centipede',
  'Chain',
  'Chainsaw',
  'Chair',
  'Chalk',
  'Change',
  'Charge',
  'Check',
  'Cheese',
  'Cherry',
  'Chest',
  'Chick',
  'China',
  'Chip',
  'Chocolate',
  'Christmas',
  'Church',
  'Circle',
  'Classroom',
  'Cleopatra',
  'Cliff',
  'Cloak',
  'Clock',
  'Cloud',
  'Club',
  'Coach',
  'Coast',
  'Coconut',
  'Code',
  'Coffee',
  'Cold',
  'Collar',
  'Columbus',
  'Comb',
  'Comet',
  'Comic',
  'Compass',
  'Compound',
  'Computer',
  'Concert',
  'Conductor',
  'Cone',
  'Console',
  'Contract',
  'Cook',
  'Copper',
  'Cotton',
  'Country',
  'Court',
  'Cover',
  'Cow',
  'Cowboy',
  'Crab',
  'Craft',
  'Crane',
  'Crash',
  'Cream',
  'Cricket',
  'Cross',
  'Crow',
  'Crown',
  'Crusader',
  'Crystal',
  'Cuckoo',
  'Cup',
  'Curry',
  'Cycle',
  'Cyclops',
  'Czech',
  'Dance',
  'Dash',
  'Date',
  'Day',
  'Death',
  'Deck',
  'Degree',
  'Delta',
  'Dentist',
  'Desk',
  'Dew',
  'Diamond',
  'Dice',
  'Dinosaur',
  'Director',
  'Disease',
  'Disk',
  'Doctor',
  'Dog',
  'Doll',
  'Dollar',
  'Dolphin',
  'Donkey',
  'Door',
  'Draft',
  'Dragon',
  'Drawing',
  'Dream',
  'Dress',
  'Dressing',
  'Drill',
  'Drive',
  'Driver',
  'Drone',
  'Drop',
  'Drum',
  'Dryer',
  'Duck',
  'Dust',
  'Dwarf',
  'Eagle',
  'Ear',
  'Earth',
  'Earthquake',
  'Easter',
  'Eden',
  'Egg',
  'Egypt',
  'Einstein',
  'Elephant',
  'Elevator',
  'Embassy',
  'Emerald',
  'Engine',
  'England',
  'Europe',
  'Eye',
  'Face',
  'Fair',
  'Fall',
  'Fan',
  'Farm',
  'Father',
  'Fence',
  'Fever',
  'Fiddle',
  'Field',
  'Fighter',
  'Figure',
  'File',
  'Film',
  'Fire',
  'Fish',
  'Flag',
  'Flash',
  'Flat',
  'Flint',
  'Flood',
  'Floor',
  'Flute',
  'Fly',
  'Foam',
  'Fog',
  'Foot',
  'Force',
  'Ford',
  'Forest',
  'Fork',
  'Formula',
  'Fox',
  'France',
  'Frog',
  'Frost',
  'Fuel',
  'Game',
  'Gangster',
  'Garden',
  'Gas',
  'Gear',
  'Genie',
  'Genius',
  'Germany',
  'Geyser',
  'Ghost',
  'Giant',
  'Glacier',
  'Gladiator',
  'Glass',
  'Glasses',
  'Globe',
  'Glove',
  'Goat',
  'Gold',
  'Goldilocks',
  'Golf',
  'Governor',
  'Grace',
  'Grass',
  'Gravity',
  'Greece',
  'Green',
  'Greenhouse',
  'Groom',
  'Ground',
  'Guitar',
  'Gum',
  'Gymnast',
  'Hacker',
  'Hair',
  'Halloween',
  'Ham',
  'Hamburger',
  'Hammer',
  'Hand',
  'Harbor',
  'Hat',
  'Hatchet',
  'Hawaii',
  'Hawk',
  'Head',
  'Heart',
  'Hedgehog',
  'Helicopter',
  'Helmet',
  'Hercules',
  'Hide',
  'Himalayas',
  'Hippopotamus',
  'Hit',
  'Hitchhiker',
  'Hole',
  'Hollywood',
  'Homer',
  'Honey',
  'Hood',
  'Hook',
  'Horn',
  'Horse',
  'Horseshoe',
  'Hose',
  'Hospital',
  'Hotel',
  'House',
  'Hunter',
  'Hurricane',
  'Ice',
  'Ice Age',
  'Ice Cream',
  'Iceland',
  'Igloo',
  'India',
  'Ink',
  'Iron',
  'Italy',
  'Ivory',
  'Jack',
  'Jaguar',
  'Jail',
  'Jam',
  'Jellyfish',
  'Jet',
  'Jeweler',
  'Joan of Arc',
  'Jockey',
  'Joker',
  'Judge',
  'Jumper',
  'Jupiter',
  'Kangaroo',
  'Ketchup',
  'Key',
  'Kick',
  'Kid',
  'Kilt',
  'King',
  'King Arthur',
  'Kiss',
  'Kitchen',
  'Kiwi',
  'Knife',
  'Knight',
  'Knot',
  'Kung Fu',
  'Lab',
  'Lace',
  'Ladder',
  'Lake',
  'Lamb',
  'Lap',
  'Laser',
  'Laundry',
  'Lava',
  'Lawyer',
  'Lead',
  'Leaf',
  'Leather',
  'Lemon',
  'Lemonade',
  'Leprechaun',
  'Letter',
  'Life',
  'Light',
  'Lighthouse',
  'Lightning',
  'Limousine',
  'Line',
  'Link',
  'Lion',
  'Lip',
  'Litter',
  'Llama',
  'Loch Ness',
  'Lock',
  'Locust',
  'Log',
  'London',
  'Love',
  'Luck',
  'Lumberjack',
  'Lunch',
  'Magazine',
  'Magician',
  'Mail',
  'Makeup',
  'Mammoth',
  'Manicure',
  'Map',
  'Maple',
  'Maracas',
  'Marathon',
  'Marble',
  'March',
  'Mark',
  'Mars',
  'Mass',
  'Match',
  'Medic',
  'Memory',
  'Mercury',
  'Mermaid',
  'Mess',
  'Meter',
  'Mexico',
  'Microscope',
  'Microwave',
  'Mile',
  'Milk',
  'Mill',
  'Millionaire',
  'Mine',
  'Minotaur',
  'Mint',
  'Minute',
  'Mirror',
  'Miss',
  'Missile',
  'Mission',
  'Model',
  'Mohawk',
  'Mole',
  'Mona Lisa',
  'Monkey',
  'Moon',
  'Moscow',
  'Moses',
  'Mosquito',
  'Mother',
  'Mount',
  'Mountie',
  'Mouse',
  'Mouth',
  'Mud',
  'Mug',
  'Mummy',
  'Musketeer',
  'Mustard',
  'Nail',
  'Napoleon',
  'Needle',
  'Nerve',
  'Net',
  'New York',
  'Newton',
  'Night',
  'Ninja',
  'Noah',
  'Nose',
  'Note',
  'Notre Dame',
  'Novel',
  'Nurse',
  'Nut',
  'Nutcracker',
  'Nylon',
  'Oasis',
  'Octopus',
  'Oil',
  'Olive',
  'Olympus',
  'Onion',
  'Opera',
  'Orange',
  'Organ',
  'Oven',
  'Pacific',
  'Pad',
  'Paddle',
  'Page',
  'Paint',
  'Palm',
  'Pan',
  'Panda',
  'Pants',
  'Paper',
  'Parachute',
  'Parade',
  'Parasite',
  'Park',
  'Parrot',
  'Part',
  'Pass',
  'Paste',
  'Patient',
  'Pea',
  'Peach',
  'Peanut',
  'Pearl',
  'Pegasus',
  'Pen',
  'Pencil',
  'Penguin',
  'Penny',
  'Pentagon',
  'Pepper',
  'Pew',
  'Phoenix',
  'Piano',
  'Pie',
  'Pig',
  'Pillow',
  'Pilot',
  'Pin',
  'Pine',
  'Pipe',
  'Pirate',
  'Pistol',
  'Pit',
  'Pitch',
  'Pitcher',
  'Pizza',
  'Plane',
  'Plant',
  'Plastic',
  'Plate',
  'Platypus',
  'Play',
  'Plot',
  'Plumber',
  'Pocket',
  'Point',
  'Poison',
  'Pole',
  'Police',
  'Polish',
  'Polo',
  'Pond',
  'Pool',
  'Pop',
  'Popcorn',
  'Port',
  'Post',
  'Postcard',
  'Potato',
  'Potter',
  'Pound',
  'Powder',
  'Press',
  'Princess',
  'Pump',
  'Pumpkin',
  'Pupil',
  'Puppet',
  'Purse',
  'Pyramid',
  'Quack',
  'Quarter',
  'Queen',
  'Rabbit',
  'Racket',
  'Radio',
  'Rail',
  'Rainbow',
  'Ram',
  'Ranch',
  'Rat',
  'Ray',
  'Razor',
  'Record',
  'Reindeer',
  'Revolution',
  'Rice',
  'Rifle',
  'Ring',
  'Rip',
  'River',
  'Road',
  'Robin',
  'Robot',
  'Rock',
  'Rodeo',
  'Roll',
  'Rome',
  'Root',
  'Rope',
  'Rose',
  'Roulette',
  'Round',
  'Row',
  'Rubber',
  'Ruby',
  'Ruler',
  'Russia',
  'Rust',
  'Sack',
  'Saddle',
  'Safari',
  'Sahara',
  'Sail',
  'Salad',
  'Saloon',
  'Salsa',
  'Salt',
  'Sand',
  'Santa',
  'Satellite',
  'Saturn',
  'Saw',
  'Scale',
  'Scarecrow',
  'School',
  'Scientist',
  'Scorpion',
  'Scratch',
  'Scream',
  'Screen',
  'Scroll',
  'Scuba Diver',
  'Seal',
  'Second',
  'Security',
  'Seed',
  'Server',
  'Shadow',
  'Shakespeare',
  'Shampoo',
  'Shark',
  'Shed',
  'Sheep',
  'Sheet',
  'Shell',
  'Sherlock',
  'Sherwood',
  'Ship',
  'Shoe',
  'Shoot',
  'Shop',
  'Shorts',
  'Shot',
  'Shoulder',
  'Shower',
  'Sign',
  'Silk',
  'Sink',
  'Sister',
  'Skates',
  'Skeleton',
  'Ski',
  'Skull',
  'Skyscraper',
  'Sled',
  'Sleep',
  'Sling',
  'Slip',
  'Slipper',
  'Sloth',
  'Slug',
  'Smell',
  'Smoke',
  'Smoothie',
  'Smuggler',
  'Snake',
  'Snap',
  'Snorkel',
  'Snow',
  'Snowman',
  'Soap',
  'Sock',
  'Soldier',
  'Soul',
  'Sound',
  'Soup',
  'Space',
  'Speedometer',
  'Spell',
  'Sphinx',
  'Spider',
  'Spike',
  'Spine',
  'Spirit',
  'Spoon',
  'Spot',
  'Spray',
  'Spring',
  'Spurs',
  'Spy',
  'Square',
  'Squash',
  'Squirrel',
  'St. Patrick',
  'Stable',
  'Stadium',
  'Staff',
  'Stamp',
  'Star',
  'State',
  'Steam',
  'Steel',
  'Step',
  'Stethoscope',
  'Stick',
  'Sticker',
  'Stock',
  'Storm',
  'Story',
  'Straw',
  'Stream',
  'Street',
  'Strike',
  'String',
  'Sub',
  'Submarine',
  'Sugar',
  'Suit',
  'Sumo',
  'Sun',
  'Sunflower',
  'Superhero',
  'Superman',
  'Swamp',
  'Sweat',
  'Swing',
  'Switch',
  'Sword',
  'Table',
  'Tablet',
  'Tag',
  'Tail',
  'Tank',
  'Tap',
  'Tarzan',
  'Taste',
  'Tattoo',
  'Taxi',
  'Tea',
  'Teacher',
  'Team',
  'Tear',
  'Telescope',
  'Temple',
  'Tent',
  'Texas',
  'Theater',
  'Thief',
  'Thorn',
  'Thumb',
  'Thunder',
  'Tick',
  'Tie',
  'Tiger',
  'Time',
  'Tin',
  'Tip',
  'Tipi',
  'Toast',
  'Tokyo',
  'Tooth',
  'Torch',
  'Tornado',
  'Toucan',
  'Tower',
  'Track',
  'Train',
  'Triangle',
  'Trick',
  'Trip',
  'Troll',
  'Trunk',
  'Tube',
  'Tunnel',
  'Turkey',
  'Turtle',
  'Tutu',
  'Tuxedo',
  'Umbrella',
  'Undertaker',
  'Unicorn',
  'Uniform',
  'University',
  'Vacuum',
  'Valentine',
  'Vampire',
  'Van',
  'Venus',
  'Vet',
  'Viking',
  'Violet',
  'Violin',
  'Virus',
  'Volcano',
  'Volume',
  'Wagon',
  'Waitress',
  'Wake',
  'Wall',
  'Walrus',
  'War',
  'Wart',
  'Washer',
  'Washington',
  'Watch',
  'Water',
  'Wave',
  'Web',
  'Wedding',
  'Well',
  'Werewolf',
  'Whale',
  'Wheel',
  'Wheelchair',
  'Whip',
  'Whistle',
  'Wind',
  'Windmill',
  'Window',
  'Wing',
  'Wire',
  'Wish',
  'Witch',
  'Wizard',
  'Wolf',
  'Wonderland',
  'Wood',
  'Wool',
  'Worm',
  'Writer',
  'Yard',
  'Yellowstone',
  'Zebra'
];

words['Custom'] = [];

words['20th Century'] = [
  "1984",
  "3D Glasses",
  "Abba",
  "Acid Rain",
  "Aerobics with Richard Simmons",
  "Amelia Earhart",
  "Apple IIe",
  "Archie Bunker's Chair",
  "Army Navy Surplus Store",
  "Artificial Heart",
  "Ascii",
  "Babe Ruth",
  "Banksy",
  "Barbie",
  "Bay of Pigs",
  "Beach Boys",
  "Beehive Hairdo",
  "Beverly Hills 90210",
  "Birkenstock Sandals",
  "Blockbuster Video",
  "Blue Light Special",
  "Bobby Pins",
  "Boombox",
  "Breadline",
  "Breakdancing",
  "Brown v. Board of Education",
  "Buddy Holly & The Crickets",
  "Bugs Bunny",
  "Buzz Cut",
  "Cabbage Patch Doll",
  "Casablanca",
  "Catcher in the Rye",
  "CB Radio",
  "CD",
  "Charlie Brown",
  "Charlie's Angels",
  "Chattanooga Choo Choo",
  "Chuck Norris",
  "Coco Chanel",
  "Coffee, Tea, or Milk?",
  "Converse All Stars",
  "Cookie Monster",
  "Dallas",
  "Dewey Defeats Truman",
  "Disco Inferno",
  "Django Reinhardt",
  "Drive-In Movie",
  "Duct Tape",
  "Electric Guitar",
  "Empire State Building",
  "Espresso",
  "FDR",
  "Floppy Disk",
  "Fonzie's Leather Jacket",
  "Ford Mustang",
  "Foxtrot",
  "Friends",
  "Frisbee",
  "G.I. Joe",
  "General Hospital",
  "Grapefruit Diet",
  "Gunsmoke",
  "Hammer Time",
  "Hanging Out at the Mall",
  "Homer Simpson",
  "Hoover Dam",
  "Hula Hoop",
  "I Have a Dream",
  "Intel Pentium",
  "Jackie Robinson",
  "Jacques Cousteau",
  "Jane Goodall",
  "Jaws",
  "Jeep",
  "JFK",
  "Johnny Cash",
  "Jumbo Jet",
  "Kermit the Frog",
  "Lego",
  "Lemonade Stand",
  "Little Orphan Annie",
  "Lucky Lindy",
  "Lucy, Holding the Football",
  "MacGyver",
  "Machine Wash, Tumble Dry",
  "Madonna",
  "Mars Lander",
  "Mary Poppins",
  "Michael Jordan",
  "Microsoft DOS",
  "Microwave Oven",
  "Mix Tape",
  "Model T",
  "Modem",
  "Monopoly",
  "Monty Python",
  "Moptop",
  "Mosh Pit",
  "Mother Teresa",
  "Neil Armstrong",
  "Neon Lights",
  "Newsreel",
  "Nylon Stockings",
  "O Canada",
  "OPEC",
  "Oprah's Book Club",
  "Pac-Man",
  "Peace Sign",
  "Penicillin",
  "Permanent Wave",
  "Pet Rock",
  "Pinball",
  "Pizza Hut",
  "Plastic Surgery",
  "Pluto Is a Planet",
  "Polaroid Camera",
  "Polio Vaccine",
  "Poodle Skirt",
  "Popeye",
  "Prohibition",
  "Propeller Beanie",
  "R.E.M.",
  "Remote Control",
  "Rock & Roll",
  "Roller Rink",
  "Rosa Parks",
  "Rosie the Riveter",
  "Route 66",
  "Rubik's Cube",
  "Satellite Dish",
  "Saturday Night Live",
  "Saved by the Bell",
  "Scooby-Doo",
  "Scopes Monkey Trial",
  "Sesame Street",
  "Simon & Garfunkel",
  "Slinky",
  "Smash Mouth",
  "Smells Like Teen Spirit",
  "Smokey the Bear",
  "Smurfs",
  "Soap Opera",
  "Sock Hop",
  "Soda Fountain",
  "Sonic Boom",
  "Sonny & Cher",
  "Sony Walkman",
  "South Pacific",
  "Space Invaders",
  "Space Shuttle",
  "Spice Girls",
  "Spruce Goose",
  "Sputnik",
  "Steve Jobs",
  "Swinging on a Star",
  "Switchboard Operator",
  "Synthesizer",
  "Tamagotchi",
  "Tarzan of the Apes",
  "Teddy Bear",
  "Tetris",
  "The $64,000 Question",
  "The Beatles",
  "The Berlin Wall",
  "The Chunnel",
  "The Cola Wars",
  "The Dust Bowl",
  "The Eagle Has Landed",
  "The Final Countdown",
  "The Flintstones",
  "The Grapes of Wrath",
  "The Grateful Dead",
  "The Honeymooners",
  "The Little Mermaid",
  "The Little Prince",
  "The Lone Ranger",
  "The Macarena",
  "The Sound of Silence",
  "The Sun Also Rises",
  "The Swedish Chef",
  "The X-Files",
  "This Lousy T-Shirt",
  "Titanic",
  "To Kill a Mockingbird",
  "Trivial Pursuit",
  "Truth or Consequences",
  "Tupperware Party",
  "Volkswagen Beetle",
  "Watergate",
  "West Side Story",
  "Where's the Beef?",
  "Who Shot J.R.?",
  "Women's Suffrage",
  "Wooden Nickel",
  "Woodstock",
  "Woodsy Owl",
  "Xena Warrior Princess",
  "Y2K",
  "Yoda"
];

words['Fantasy'] = [
  "A Midsummer Night's Dream",
  "Airbender",
  "Aladdin's Lamp",
  "Alchemists",
  "Anansi the Spider",
  "Aragorn",
  "Arwen Evenstar",
  "Asterix & Obelix",
  "Axe Throwing",
  "Beauty & The Beast",
  "Bibbidi-Bobbidi-Boo",
  "Big Bad Wolf",
  "Big Trouble in Little China",
  "Bilbo Baggins",
  "Book of the Dead",
  "Broken Earth",
  "Buffy the Vampire Slayer",
  "Building Sandcastles",
  "Butterbeer",
  "Camelot",
  "Captain Hook",
  "Cerberus",
  "Chain Mail",
  "Charlie & The Chocolate Factory",
  "Charon the Boatman",
  "Chuck Norris",
  "Circles of Hell",
  "Count Dracula",
  "Coyote the Trickster",
  "Critical Role",
  "Crystal Ball",
  "Cthulhu",
  "Deal with the Devil",
  "Deck of Many Things",
  "Diabolic Laughter",
  "Dobby the House Elf",
  "Down the Rabbit Hole",
  "Dragonriders of Pern",
  "Drink Me",
  "Dungeon Master",
  "Earthbender",
  "Eye of Sauron",
  "Fighter Fred",
  "Filking",
  "Finn's Pack",
  "Firebender",
  "Five Nights at Freddy's",
  "Forty Thieves",
  "Friendship Is Magic",
  "Gandalf",
  "Gargoyle",
  "Gelatinous Cube",
  "Gingerbread House",
  "Girl Genius",
  "Glass Slipper",
  "Golden Egg",
  "Golden Fleece",
  "Gollum",
  "Good Omens",
  "Granny Weatherwax",
  "Greg the Garlic Farmer",
  "Gringotts Bank",
  "Harry Dresden, Wizard P.I.",
  "Harry Potter",
  "Have Fun Storming the Castle",
  "Hellboy",
  "Hermione Granger",
  "Hiccup & Toothless",
  "Hogwarts",
  "Home for Peculiar Children",
  "I Am Not Left Handed",
  "Imaginary Friend",
  "Into the Woods",
  "Invisibility Cloak",
  "Iron Throne",
  "Jack & The Beanstalk",
  "Jack Frost",
  "Jake the Dog",
  "Jousting",
  "King Midas",
  "Kiss the Frog",
  "Knights Who Say Ni!",
  "Labyrinth",
  "Ladyhawke",
  "LARP",
  "Launched 1000 Ships",
  "Legolas",
  "Lembas Bread",
  "Let It Go",
  "Loch Ness Monster",
  "Mad Hatter",
  "Magic Carpet",
  "Mary Poppins",
  "Medusa",
  "Mercy Thompson, Car Mechanic",
  "Merlin",
  "Mines of Moria",
  "Mirror Mirror",
  "Mischief Managed",
  "Mistborn",
  "Mistletoe",
  "Munchkin",
  "My Name Is Inigo Montoya",
  "Nazgul",
  "Necromancer",
  "Neptune",
  "Odin",
  "Off with Her Head",
  "One Night Ultimate Werewolf",
  "One Piece",
  "Open Sesame",
  "Order of the Stick",
  "Pandora's Box",
  "Penelope's Loom",
  "Peter Pan",
  "Pinocchio",
  "Play Chess with Death",
  "Porridge Is Just Right",
  "Potion of Gaseous Form",
  "Potion of Giant Strength",
  "Princess Bubblegum",
  "Puss in Boots",
  "Queen of Hearts",
  "Quidditch",
  "Quoth the Raven",
  "Rapunzel",
  "Red Riding Hood",
  "Release the Kraken",
  "Ride of the Valkyries",
  "Robin Hood",
  "Ruby Slippers",
  "Sandman",
  "Scheherazade",
  "Secret Door",
  "Shadow & Bone",
  "Shaolin Kung Fu",
  "Sherwood Forest",
  "Shrieking Shack",
  "Simply Walk into Mordor",
  "Skyrim",
  "Smurfette",
  "Sorting Hat",
  "Stay-Puft Marshmallow Man",
  "Stole Fire from the Gods",
  "Stormlight",
  "Straw into Gold",
  "Sword of Damocles",
  "Team Edward",
  "Team Jacob",
  "The Black Cauldron",
  "The Black Pearl",
  "The Cowardly Lion",
  "The Dark Crystal",
  "The Dark Tower",
  "The Golden Compass",
  "The Headless Horseman",
  "The Holy Grail",
  "The Holy Hand Grenade",
  "The Last Unicorn",
  "The Little Mermaid",
  "The Little Prince",
  "The Nutcracker",
  "The One Ring",
  "The River Styx",
  "The Road Goes Ever On & On",
  "The Spiderwick Chronicles",
  "The Tortoise & The Hare",
  "The Witcher",
  "Thorin Oakenshield",
  "Time Turner",
  "Tin Woodman",
  "Tinkerbell",
  "Tom Thumb",
  "Too Close to the Sun",
  "Training Montage",
  "Tree of Life",
  "Treebeard",
  "Turn into a Pumpkin",
  "Twilight Sparkle",
  "Ugly Duckling",
  "Unseen University",
  "Valhalla",
  "Vote to Bell the Cat",
  "Waterbender",
  "Wednesday Addams",
  "Wheel of Time",
  "Where the Wild Things Are",
  "Where Was Gondor?",
  "Whomping Willow",
  "Wingardium Leviosa",
  "Winged Monkeys",
  "Winter Is Coming",
  "World on the Back of a Turtle",
  "Xena Warrior Princess",
  "Yellow Brick Road",
  "You Shall Not Pass!",
  "Zeus",
  "Zombie Apocalypse"
];

words['History'] = [
  "Abraham Lincoln",
  "Acupuncture",
  "Alexander the Great",
  "Angkor Wat",
  "Antony & Cleopatra",
  "Battle of Britain",
  "Bering Land Bridge",
  "Bethlehem",
  "Bishop Desmond Tutu",
  "Black Tuesday",
  "Blackbeard",
  "Boxer Rebellion",
  "Bronze Age",
  "Butter Churn",
  "Cahokia Mounds",
  "Carrier Pigeon",
  "Chain Mail",
  "Charge of the Light Brigade",
  "Chariot Race",
  "Chicxulub Crater",
  "Chimney Sweep",
  "Chuck Norris",
  "Clovis Point",
  "Combination Harvester",
  "Comenius",
  "Copernicus",
  "Cotton Gin",
  "Court Jester",
  "Cowpox Vaccination",
  "Crop Rotation",
  "Crossbow",
  "Cuneiform",
  "D-Day",
  "Dead Sea Scrolls",
  "Domestication of the Reindeer",
  "Dr. Livingstone, I Presume?",
  "Draco's Code",
  "Elizabeth II",
  "Et Tu, Brute?",
  "Eureka!",
  "FDR",
  "Fencing",
  "Ferdinand Magellan",
  "Florence Nightingale",
  "Footman",
  "Fountain of Youth",
  "Gandhi",
  "Genghis Khan",
  "Gold Rush",
  "Gothic Cathedral",
  "Graffiti",
  "Great Wall of China",
  "Great Zimbabwe",
  "Greek Chorus",
  "Gregorian Chant",
  "Gunpowder",
  "Hadrian's Wall",
  "Hannibal Crossing the Alps",
  "Harpsichord",
  "Henry VIII",
  "Hieroglyphs",
  "Hippocrates",
  "Horse Collar",
  "Hudson's Bay Company",
  "Hunter-Gatherers",
  "I Am Spartacus",
  "I Have a Dream",
  "Icebox",
  "Icelandic Sagas",
  "Inca Rope Bridges",
  "Industrial Revolution",
  "Invisible Hand",
  "Iron Curtain",
  "Jar of Leeches",
  "JFK",
  "Julius Caesar",
  "Kamikaze",
  "Katana",
  "Lacrosse",
  "Lamplighter",
  "Lascaux Cave Paintings",
  "Launched 1000 Ships",
  "Leonardo da Vinci",
  "Let Them Eat Cake!",
  "Lewis & Clark",
  "Little Bighorn",
  "London Bridge",
  "Macedonian Phalanx",
  "Magna Carta",
  "Mandate of Heaven",
  "Marco Polo",
  "Maya Calendar",
  "Mendel's Peas",
  "Michelangelo",
  "Ming Vase",
  "Moat",
  "Moldboard Plow",
  "Mount Vesuvius",
  "Mysorean Rockets",
  "NASA",
  "Nelson Mandela",
  "Nguni Shield",
  "Nomadic Herders",
  "Nose of the Sphinx",
  "Olmec Head",
  "Olympic Games",
  "Oregon Trail",
  "Pangaea",
  "Parthian Shot",
  "Pasteurization",
  "Patchwork Quilt",
  "Peace Pipe",
  "Pearl Harbor",
  "Penal Colony",
  "Phlogiston",
  "Plains of Marathon",
  "Plains Sign Talk",
  "Plato's Republic",
  "Pocahontas",
  "Polynesian Expansion",
  "Pony Express",
  "Potemkin Village",
  "Powdered Wig",
  "Printing Press",
  "Pythagoras",
  "Queen Hatshepsut",
  "Quill Pen",
  "Radio Free Europe",
  "Ragtime",
  "Richard the Lionheart",
  "Ride of the Valkyries",
  "Roanoke Colony",
  "Romulus & Remus",
  "Rosetta Stone",
  "Sacred Cows",
  "Saladin",
  "Salem Witch Trials",
  "Salvador Dalí",
  "Schindler's List",
  "Shoulders of Giants",
  "Silkworm",
  "Silversmith",
  "Songlines",
  "Soviet Union",
  "Spanish Armada",
  "Spinning Wheel",
  "Sputnik",
  "Steam Engine",
  "Stone Age",
  "Stonehenge",
  "Sundial",
  "Tanning Hides",
  "Telegraph",
  "Terracotta Army",
  "The Alamo",
  "The Bavarian Illuminati",
  "The Berlin Airlift",
  "The Boston Tea Party",
  "The Cold War",
  "The Colosseum",
  "The Colossus of Rhodes",
  "The Crown Jewels",
  "The Fertile Crescent",
  "The Forbidden City",
  "The Great Pyramid",
  "The Hanging Gardens",
  "The Holy Grail",
  "The Inquisition",
  "The Last Supper",
  "The Leaning Tower of Pisa",
  "The Library of Alexandria",
  "The Lighthouse of Alexandria",
  "The Night Witches",
  "The Prague Spring",
  "The Red Baron",
  "The Taj Mahal",
  "The Ten Commandments",
  "The Velvet Revolution",
  "Theory of Chakras",
  "Theory of Evolution",
  "Theory of Humours",
  "Tigris & Euphrates",
  "Toga",
  "Total War",
  "Trebuchet",
  "Trireme Rower",
  "Trojan Horse",
  "Tycho's Supernova",
  "U-Boat",
  "Ur",
  "Urban Plumbing",
  "Vandals",
  "Venus of Willendorf",
  "Viennese Waltz",
  "War of the Roses",
  "Waterloo",
  "Wheelwright",
  "Winston Churchill",
  "Yuri Gagarin",
  "Zeppelin"
];

words['Modern'] = [
  "3D Printer",
  "Accessibility Ramp",
  "Alibaba",
  "Amazon.com",
  "Art Mug on Etsy",
  "Artificial Intelligence",
  "Audiobook",
  "Avocado Toast",
  "Baby Shark",
  "Baby Yoda",
  "Bad Bunny",
  "Banana Republic",
  "Banksy",
  "Beauty Blog",
  "Bike Share System",
  "Biometric Authentication",
  "Bitcoin",
  "Blackpink",
  "Blue's Clues",
  "Bluetooth",
  "Boardgame Cafe",
  "BoardGameGeek",
  "Brick & Mortar",
  "Bullet Train",
  "Call Me Maybe",
  "Can I DM You?",
  "Candy Crush",
  "Carbon Footprint",
  "ChatGPT",
  "Cheesecake",
  "Chicken Tikka Masala",
  "Chuck Norris",
  "Citation Needed",
  "Click, Like, & Subscribe",
  "Cloud Storage",
  "Cocomelon",
  "Comic Sans",
  "Crazy Frog",
  "Critical Role",
  "Crocs",
  "Dark Web",
  "Delivery Drone",
  "Discord Server",
  "Do You Even Lift?",
  "Doctor House",
  "Does It Spark Joy?",
  "Dog Walker",
  "Doge",
  "Doordash",
  "Dying Battery",
  "Elizabeth II",
  "Elon Musk",
  "Embarrassing YouTube Ad",
  "Emoji",
  "Escape Room",
  "Every Day I'm Shufflin'",
  "Facetime",
  "Farmers Market",
  "Fashion Police",
  "Feng Shui",
  "Gangnam Style",
  "Geothermal Energy",
  "Google Earth",
  "GPS",
  "Graffiti",
  "Grumpy Cat",
  "Hashtag",
  "Hip-Hop",
  "Hipster",
  "Honest Trailers",
  "Honey Badger",
  "Hostile Architecture",
  "How Ridiculous",
  "Ikea",
  "Illegal Deck Barbecue",
  "Ima Come Back Like a Boomerang",
  "Ima Light It Up Like Dynamite",
  "Imagine Dragons",
  "Instagram",
  "International Space Station",
  "Is Die Hard a Christmas Movie?",
  "Is Leia a Disney Princess?",
  "Jamba Juice",
  "Jeggings",
  "Karaoke",
  "Key & Peele",
  "Kickstarter",
  "Kindle Paperwhite",
  "LARP",
  "Lego",
  "Low-Floor Bus",
  "Mars Lander",
  "Marshmello",
  "Masterchef",
  "May the Fourth",
  "Midjourney",
  "Mommy Bloggers",
  "More Cowbell!",
  "Motorized Scooter",
  "Moving Sidewalk",
  "MrBeast",
  "Nail Art Pen",
  "NASA",
  "Nerf Gun",
  "Netflix",
  "New Phone, Who Dis?",
  "Nickelback",
  "Night Vision Goggles",
  "No Tears Left to Cry",
  "Noise-Canceling Headphones",
  "Obvious Password",
  "Ocean Eyes",
  "Old Town Road",
  "One Piece",
  "One Weird Trick",
  "Only Girl in the World",
  "Orange Is the New Black",
  "Osprey Nest Webcam",
  "Out of Office Reply",
  "Paleo Diet",
  "Parkour",
  "Parks & Recreation",
  "Paypal",
  "Peloton Instructor",
  "PewDiePie",
  "Philosoraptor",
  "Phishing",
  "Photoshop",
  "Pinterest",
  "Pluto Is Not a Planet",
  "Podcast",
  "Political Facebook Rant",
  "Porch Pirates",
  "Privacy Policy",
  "Prove You're Not a Robot",
  "Red Bull",
  "Red Hot Ball Videos",
  "Remote Learning",
  "Rickroll",
  "Rosetta Stone",
  "Rotten Tomatoes",
  "Said No One Ever",
  "Saturday Night Live",
  "Scared to Be Lonely",
  "Scrapbooking",
  "Self-Driving Car",
  "Selfie Stick",
  "Sesame Oil",
  "Set Fire to the Rain",
  "Shake It Off",
  "Shelfie",
  "Shoulda Put a Ring on It",
  "Shut Up & Dance with Me",
  "Sidewalk Art",
  "Simply Walk into Mordor",
  "Smartwatch",
  "Snapchat",
  "Solar Panels",
  "Sorry, Butt Dial",
  "Space Tourism",
  "Space Unicorn",
  "Spam",
  "Spotify",
  "Squid Game",
  "Sriracha Hot Sauce",
  "Starbucks",
  "Step 3: Profit!",
  "Stupid Autocorrect",
  "T-Series",
  "Taco Truck",
  "Taylor Swift",
  "That Place Is Sketch",
  "The Large Hadron Collider",
  "The Queen's Gambit",
  "The Weeknd",
  "This Is Spartaaa!",
  "Tiktok",
  "Tinfoil Hat",
  "Try Not to Laugh",
  "Twitch Stream",
  "Two Bars of Signal",
  "Uber",
  "Ugh, Swipe Left!",
  "Unused Gym Membership",
  "Urban Gardening",
  "USB",
  "VR Headset",
  "Waterstones",
  "Wedding Planner",
  "Where's My Flying Car?",
  "Which My Little Pony Are You?",
  "Wi-Fi Hotspot",
  "Wikipedia",
  "Wind Farm",
  "Xkcd",
  "Y2K",
  "Yelp",
  "You Won't Believe ...",
  "You're the Sunflower",
  "Zombie Nation",
  "Zoom Meeting"
];

words['Movies'] = [
  "3:10 to Yuma",
  "76 Trombones",
  "A Fistful of Dollars",
  "A Raisin in the Sun",
  "A Streetcar Named Desire",
  "Alfred Hitchcock",
  "All Outta Bubblegum",
  "Amadeus",
  "American Grafitti",
  "Anchorman",
  "Apocalypse Now",
  "Back to the Future",
  "Bambi",
  "Barbie",
  "Bend It Like Beckham",
  "Benjamin Button",
  "Bibbidi-Bobbidi-Boo",
  "Black Panther",
  "Black Widow",
  "Blackboard Jungle",
  "Bogart's Fedora",
  "Bollywood",
  "Bond, James Bond",
  "Boom Mic",
  "Braveheart",
  "Breakfast at Tiffany's",
  "Bridges of Madison County",
  "Bridget Jones's Diary",
  "Buzz Lightyear",
  "Cannonball Run",
  "Captain Jack Sparrow",
  "Casablanca",
  "Chariots of Fire",
  "Chuck Norris",
  "Clash of the Titans",
  "Cliffhanger",
  "Climb Ev'ry Mountain",
  "Coal Miner's Daughter",
  "Conan the Barbarian",
  "Cool Runnings",
  "Count Dracula",
  "Crazy Rich Asians",
  "Crocodile Dundee",
  "Cut!",
  "Dead Poets Society",
  "Deadpool",
  "Deus Ex Machina",
  "Dirty Dancing",
  "Doctor Zhivago",
  "Dolly Grip",
  "Donald Duck",
  "Driving Miss Daisy",
  "Dumbo",
  "E.T. Phone Home",
  "Easy Rider",
  "Everything Is Awesome!",
  "Facial Motion Capture",
  "Fiddler on the Roof",
  "Field of Dreams",
  "Fix It in Post",
  "Frankenstein",
  "Frozen",
  "Full Metal Jacket",
  "Ghostbusters",
  "Godzilla",
  "Grease",
  "Green Screen",
  "Gremlins",
  "Groundhog Day",
  "Hacksaw Ridge",
  "Hairspray",
  "Harry Potter",
  "Harvey the Invisible Rabbit",
  "Hi Ho!",
  "Hidden Figures",
  "High School Musical",
  "Honey, Where Are My Pants?",
  "I Am Spartacus",
  "I Coulda Been a Contender",
  "I See Dead People",
  "I'll Be Back!",
  "Independence Day",
  "Indiana Jones",
  "Iron Man",
  "Is Die Hard a Christmas Movie?",
  "Is Leia a Disney Princess?",
  "Jaws",
  "Jumanji",
  "Jurassic Park",
  "Key Grip",
  "Killers of the Flower Moon",
  "Kindergarten Cop",
  "King Kong",
  "L.A. Story",
  "Lawrence of Arabia",
  "League of Their Own",
  "Life Is Beautiful",
  "Life Is Like a Box of Chocolates",
  "Lightning McQueen",
  "Lord of the Rings",
  "M*A*S*H",
  "Madagascar",
  "Mean Girls",
  "Men in Black",
  "MGM Lion",
  "Mickey Mouse",
  "Million Dollar Baby",
  "Miracle on 34th Street",
  "Moneyball",
  "Mr. Bean",
  "Mr. Smith Goes to Washington",
  "Muriel's Wedding",
  "Mutiny on the Bounty",
  "My Fair Lady",
  "No Place Like Home",
  "Ocean's 11",
  "Oh, What a Beautiful Mornin'",
  "Oscar",
  "Paint Your Wagon",
  "Plot Armor",
  "Pluto & Goofy Are Both Dogs",
  "Pocahontas",
  "Rambo",
  "Release the Kraken",
  "Right Here in River City",
  "Rocky",
  "Rosebud",
  "Rosencrantz & Guildenstern",
  "Rotten Tomatoes",
  "Run, Forrest, Run!",
  "Saving Private Ryan",
  "Schindler's List",
  "Seven Samurai",
  "Shrek",
  "Silent Film",
  "Silverado",
  "Singin' in the Rain",
  "Sixteen Candles",
  "Sleeping Beauty",
  "Sleepless in Seattle",
  "Slow Motion",
  "Slumdog Millionaire",
  "Smokey & The Bandit",
  "Snow White & The 7 Dwarfs",
  "Soft Focus Lens",
  "Some Enchanted Evening",
  "Star Trek",
  "Star Wars",
  "Steel Magnolias",
  "Sunrise, Sunset",
  "Teenage Mutant Ninja Turtles",
  "Terminator",
  "That's a Wrap",
  "The Blair Witch Project",
  "The Color Purple",
  "The Dark Knight",
  "The Devil Wears Prada",
  "The Dirty Dozen",
  "The Fault in Our Stars",
  "The Flash",
  "The Godfather",
  "The Good, the Bad, & the Ugly",
  "The Graduate",
  "The Hunger Games",
  "The Hunt for Red October",
  "The Karate Kid",
  "The Maltese Falcon",
  "The Martian",
  "The Matrix",
  "The Notebook",
  "The Red Carpet",
  "The Shape of Water",
  "The Ten Commandments",
  "The Time Traveler's Wife",
  "The Untouchables",
  "Thelma & Louise",
  "There Can Be Only One",
  "There Is No Spoon",
  "There's No Crying in Baseball",
  "This Amp Goes to 11",
  "This Is Spartaaa!",
  "Thunderball",
  "Titanic",
  "Top Gun",
  "Toy Story",
  "Tron",
  "Twilight",
  "Two Thumbs Up",
  "Wall-E",
  "Weta Workshop",
  "What's Up, Doc?",
  "Win One for the Gipper",
  "Winnie the Pooh",
  "Wizard of Oz",
  "Wolverine",
  "Wonder Woman",
  "Wreck-It Ralph",
  "Yellow Submarine",
  "You Shall Not Pass!",
  "You've Got Mail"
];

words['Nature'] = [
  "4-Chambered Heart",
  "A Sand Country Almanac",
  "Acorn Woodpecker",
  "Aftershocks",
  "Amazon Rain Forest",
  "Amoeba",
  "Angelfish",
  "Antarctic Circle",
  "Archaeopteryx",
  "Arctic Ocean",
  "Armadillo",
  "Army Ants",
  "Bald Eagle",
  "Barrel Cactus",
  "Beaver Dam",
  "Belted Kingfisher",
  "Binoculars",
  "Black Widow",
  "Blue Whale",
  "Bluegrass",
  "Bottlenose Dolphin",
  "Budding",
  "Building Sandcastles",
  "Bush Tucker",
  "California Chaparral",
  "Cambrian Explosion",
  "Campfire",
  "Canada Goose",
  "Carbon Footprint",
  "Century Plant",
  "Charles Darwin",
  "Chelyabinsk Meteor",
  "Cherry Blossom Festival",
  "Chewing Cud",
  "Chicxulub Crater",
  "Chitinous Exoskeleton",
  "Chuck Norris",
  "Clam Digging",
  "Cloven Hoof",
  "Club Mosses",
  "Coelacanth",
  "Conch Shell",
  "Coriolis Effect",
  "Crazy Lace Agate",
  "Crescent Moon",
  "Dandelion",
  "Dead Sea",
  "Death Cap Mushroom",
  "Dew Point",
  "Diamondback Rattlesnake",
  "Dogsled",
  "Double Rainbow",
  "Ducklings in a Row",
  "East African Rift",
  "Echolocation",
  "Electric Eel",
  "Elephant's Trunk",
  "Emperor Penguin",
  "Eye of the Hurricane",
  "Falling Leaves",
  "Firefly",
  "Fishing Hat",
  "Fjords of Norway",
  "Florida Everglades",
  "Following Tracks",
  "Fossilization",
  "Frozen Mammoth",
  "Galapagos Tortoise",
  "Ganges",
  "Geocaching",
  "Giant's Causeway",
  "Glacial Moraine",
  "Gold Dust",
  "Golf Ball Sized Hail",
  "Grand Canyon",
  "Grass-Stained Knees",
  "Great Barrier Reef",
  "Great Salt Lake",
  "Groundhog Day",
  "Gulf of Mexico",
  "Hammerhead Shark",
  "Hibernation",
  "Hiking Boots",
  "Hip Waders",
  "Hollow Bones",
  "Honey Badger",
  "Horizon",
  "Horseback Riding",
  "Horseshoe Crab",
  "Hot Enough to Fry an Egg",
  "Hot Springs",
  "Hummingbird",
  "Ice Jam",
  "Jacques Cousteau",
  "Jane Goodall",
  "Joshua Tree",
  "Kayaker",
  "Keystone Species",
  "King Cobra",
  "Komodo Dragon",
  "Ladybug",
  "Lake Superior",
  "Lemmings",
  "Magellanic Clouds",
  "Magnifying Glass",
  "Mangrove Swamp",
  "Mauna Loa",
  "Mediterranean Scrub",
  "Mendel's Peas",
  "Merlin",
  "Migration",
  "Milky Way",
  "Mistletoe",
  "Mitosis & Meiosis",
  "Monarch Butterfly",
  "Mongolian Steppe",
  "Mosquito Bite",
  "Mount Fuji",
  "Narwhal Tusk",
  "Niagara Falls",
  "Nightingale",
  "Nile River",
  "Nitrogen-Fixing Bacteria",
  "Northern Lights",
  "Ocean Current",
  "Opossum",
  "Opposable Thumb",
  "Orienteering",
  "Orion's Sword",
  "Osprey Nest Webcam",
  "Pack Llama",
  "Pair Bonding",
  "Pando the Aspen Grove",
  "Pangaea",
  "Photosynthesis",
  "Pine Needles",
  "Plate Tectonics",
  "Pleiosaur",
  "Polar Bear",
  "Prairie",
  "Praying Mantis",
  "Prehensile Tail",
  "Pronghorn Antelope",
  "Pufferfish",
  "Queen Bee",
  "Rail Trails",
  "Red Sea",
  "Red Skies at Morning",
  "Redwood Forest",
  "Rocky Mountains",
  "Rod & Reel",
  "Rotting Log",
  "Sabertooth Tiger",
  "Sailing Stones",
  "Sand Dollar",
  "Shepherd",
  "Shooting Star",
  "Silkworm",
  "Sirius",
  "Sleeping Bag",
  "Smokey the Bear",
  "Snowshoes",
  "Solar Eclipse Glasses",
  "Southern Cross",
  "Spelunking",
  "Spore",
  "Spring Flood",
  "Stalactite",
  "Sunbird",
  "T-Rex",
  "Tarantula",
  "Tasmanian Devil",
  "Thunder & Lightning",
  "Tornado Alley",
  "Tree of Life",
  "Triceratops",
  "Trilobite",
  "Truffle Hunting",
  "Trumpeter Swan",
  "Twilight",
  "Ultraviolet Radiation",
  "Underground Stream",
  "Urban Gardening",
  "Ursa Major",
  "Venus Flytrap",
  "Walking Catfish",
  "Warm-Blooded",
  "Warning Call",
  "Water Cycle",
  "Weather Vane",
  "Weeping Willow",
  "Wheelbarrow",
  "Wildlife Photography",
  "Wingspan",
  "Wolverine",
  "Wombat Burrow",
  "Woodsy Owl",
  "Xylem & Phloem",
  "Yellowstone National Park"
];

words['Sci-Fi'] = [
  "1984",
  "3 Laws of Robotics",
  "42",
  "Acid Rain",
  "Airlock",
  "Antimatter Reactor",
  "Artemis Bridge Simulator",
  "Artificial Intelligence",
  "Asteroid Belt",
  "Attack of the 50 Foot Woman",
  "Avatar",
  "Babel Fish",
  "Babylon 5",
  "Base Inside a Volcano",
  "Batmobile",
  "Battle of Hoth",
  "Battlestar Galactica",
  "Beam Me Up",
  "Ben Grimm, the Thing",
  "Big Brother",
  "Bionic Arm",
  "Black Mirror",
  "Blade Runner",
  "Blaster",
  "Blue Milk",
  "Bones Mccoy",
  "Borg Cube",
  "Butterfly Effect",
  "Buy It, Use It, Break It, Fix It.",
  "C-3PO",
  "Cantina Band",
  "Captain Nemo",
  "Chuck Norris",
  "Cloud Atlas",
  "Copernicus",
  "Crab Nebula",
  "Crop Circles",
  "Crow T. Robot",
  "Cryosleep",
  "Dark Matter",
  "Darth Vader",
  "Death Star",
  "DeLorean",
  "Doctor Frankenstein",
  "Doctor Who",
  "Doctor Zoidberg",
  "Dr. Jekyll & Mr. Hyde",
  "Dragonriders of Pern",
  "Dune",
  "Dyson Sphere",
  "E.T. Phone Home",
  "Electromagnetic Pulse",
  "Ender's Game",
  "Eve Online",
  "Event Horizon",
  "Ewoks",
  "Exterminate!",
  "Fahrenheit 451",
  "Faster Than Light",
  "Feed Me, Seymour",
  "Firefly",
  "First Contact",
  "Flash Gordon",
  "Flying Purple People Eater",
  "Flying Saucer",
  "Force Field",
  "Galaxy Trucker",
  "Generation Ship",
  "Genetic Engineering",
  "Ghost in the Shell",
  "Gonna Be a Long, Long Time",
  "Grabthar's Hammer",
  "Gravitational Slingshot",
  "Ground Control to Major Tom",
  "Hal 9000",
  "Han Solo",
  "Hitchhiker's Guide",
  "Holodeck",
  "Hoverboard",
  "Hydroponic Garden",
  "I Am Groot",
  "I Am Your Father",
  "Imperial March",
  "Infinity Stones",
  "Invisible Plane",
  "Jabba the Hutt",
  "Jawa",
  "Jedi Knight",
  "Jurassic Park",
  "Kerbal Space Program",
  "Killbot Hellscape",
  "Kryptonite",
  "Lieutenant Data",
  "Live Long & Prosper",
  "Lost in Space",
  "Luke Skywalker",
  "Lyra",
  "Mad Max",
  "Magellanic Clouds",
  "Magnetic Boots",
  "Marvin the Martian",
  "May the Fourth",
  "Medical Tricorder",
  "Meteor Shower",
  "Millennium Falcon",
  "Moonraker",
  "Mulder & Scully",
  "Mutant Powers",
  "Neptune",
  "Newspeak",
  "Nuclear Winter",
  "Orion's Sword",
  "Photon Torpedoes",
  "Pigs in Spaaace!",
  "Planet of the Apes",
  "Princess Leia",
  "Protons & Neutrons",
  "Pulsar",
  "Q",
  "Quantum Entanglement",
  "Quark",
  "R2-D2",
  "Ready Player One",
  "Red Dwarf",
  "Redshirt",
  "Rey's Lightsaber",
  "Ringworld",
  "River Tam",
  "Robocop",
  "RoboRally",
  "Robot Spider Legs",
  "Rocket Raccoon",
  "Sandworm",
  "Seed Bank",
  "SETI",
  "Sirius",
  "Six Million Dollar Man",
  "Solar Wind",
  "Sonic Screwdriver",
  "Space Elevator",
  "Space Jam",
  "Space Janitors",
  "Space Opera",
  "Spice Must Flow",
  "Squid Game",
  "Stargate",
  "Starship Captains",
  "Steampunk",
  "Stormtrooper",
  "String Theory",
  "Tardis",
  "Tatooine Podraces",
  "Terraforming Mars",
  "The Fifth Element",
  "The Final Countdown",
  "The Great Pyramid",
  "The Hunger Games",
  "The Incredible Hulk",
  "The Iron Giant",
  "The Klingon Homeworld",
  "The Left Hand of Darkness",
  "The Mandalorian",
  "The Matrix",
  "The Murderbot Diaries",
  "The Nautilus",
  "The Saint of Bright Doors",
  "The Satellite of Love",
  "The Sirens of Titan",
  "The Three-Body Problem",
  "The Thunderdome",
  "The Trouble with Tribbles",
  "The Truth Is Out There",
  "The Twilight Zone",
  "Tie Fighter",
  "Time Machine",
  "Titanium",
  "Too Close to the Sun",
  "Total Eclipse",
  "Transfer Window",
  "Transformers",
  "Treeship",
  "Triffid",
  "Twins Paradox",
  "Tycho's Supernova",
  "Unobtanium",
  "Uplift",
  "Upload Your Brain",
  "USS Enterprise",
  "Vogon Poetry",
  "Vulcan",
  "War of the Worlds",
  "Warhammer 40,000",
  "Westworld",
  "Where's My Flying Car?",
  "Wolf 359",
  "Wookieepedia",
  "Wormhole",
  "Yoda",
  "Zeppelin",
  "Zombie Apocalypse"
];

words['Sports'] = [
  "3 Yards & A Cloud of Dust",
  "3000 Meter Steeplechase",
  "7-10 Split",
  "Aerobics with Richard Simmons",
  "Aintree Racecourse",
  "American Pharaoh",
  "Armchair Quarterback",
  "Astroturf",
  "Athlete's Foot",
  "Axe Throwing",
  "Babe Ruth",
  "Back Door Slider",
  "Back Handspring",
  "Banana Kick",
  "Bank Shot",
  "Barrel Racing",
  "Bend It Like Beckham",
  "Biathlon",
  "Bicycle Kick",
  "Billie Jean King",
  "Birdie",
  "Black Belt",
  "Bring In a Ringer",
  "Bullseye",
  "Bump, Set, Spike!",
  "Bungee Jumping",
  "Busted Bracket",
  "Butterfly Stroke",
  "Called on Account of Rain",
  "Camel Spin",
  "Capture the Flag",
  "Cartwheel",
  "Catcher's Mitt",
  "Cauliflower Ear",
  "Chariots of Fire",
  "Cheerleader",
  "Cheese Rolling",
  "Chess Boxing",
  "Chuck Norris",
  "Churchill Downs",
  "Clay Pigeon",
  "Coffin Corner Punt",
  "Concussion Protocol",
  "Corner Pocket",
  "Cornhole",
  "Couch Potato",
  "Cricket Bat",
  "Curling",
  "Dartboard",
  "Demolition Derby",
  "Dish Off to a Teammate",
  "Dogsled",
  "Doink Off the Crossbar",
  "Dolphin Kick",
  "Eddie the Eagle",
  "Eden Gardens",
  "Eight Ball",
  "Face Off",
  "Face Painting",
  "Fantasy League",
  "Fencing",
  "Field of Dreams",
  "Float Serve",
  "Floor Routine",
  "Garbage Time",
  "Gatorade",
  "Giant Slalom",
  "Goalie Mask",
  "Goblet Squats",
  "Golf Cart",
  "Greco-Roman Wrestling",
  "Hail Mary Pass",
  "Half-Pipe",
  "Halftime Show",
  "Hall of Fame",
  "Hat Trick",
  "High Off the Glass",
  "Highland Games",
  "Hole in One",
  "Horseback Riding",
  "Hospital Pass",
  "Ice Pack",
  "Indianapolis 500",
  "Ironman Triathlon",
  "Jackie Robinson",
  "Jamaican Bobsled Team",
  "Jesse Owens",
  "Jim Thorpe's Medals",
  "Jousting",
  "Karate Chop",
  "Kayaker",
  "Kettlebell",
  "Kiss Cam",
  "Knockout Punch",
  "Knuckleball",
  "Lacrosse",
  "Laurel Wreath",
  "Lawn Mower Racing",
  "Madden NFL",
  "March Madness",
  "Marching Band",
  "Michael Jordan",
  "Mouthguard",
  "Move the Chains",
  "Muhammad Ali",
  "Nickelback",
  "Nutmeg the Defender",
  "Olympic Games",
  "Orienteering",
  "Out at the Plate",
  "Pancake Save",
  "Parkour",
  "Pebble Beach Golf Links",
  "Pelé",
  "Penalty Shootout",
  "Photo Finish",
  "Pit Stop",
  "Pool Table",
  "Quidditch",
  "Rainbow Jersey",
  "Red Card",
  "Redshirt Freshman",
  "Replay Review",
  "Rhythmic Gymnastics",
  "Rocket Handball",
  "Rookie with a High Ceiling",
  "Round Robin",
  "Running of the Bulls",
  "Sabermetrics",
  "Sachin Tendulkar",
  "Safe at Home",
  "Salary Cap",
  "Sand Trap",
  "Scorpion Kick",
  "Seam Bowler",
  "Second Wind",
  "Served an Ace",
  "Shaolin Kung Fu",
  "Sherrin Kangaroo",
  "Skate Park",
  "Ski Lift",
  "Sneakers",
  "Snowboard",
  "Southpaw",
  "Space Jam",
  "Speed Skating",
  "Square Leg",
  "St. Moritz",
  "Starting Pistol",
  "Stiff Arm",
  "Stumps & Bails",
  "Sudden Death",
  "Sumo Wrestlers",
  "Super Bowl",
  "Surfboard",
  "Synchronized Swimming",
  "Tables, Ladders, & Chairs",
  "Tailgate Barbecue",
  "Tatooine Podraces",
  "Team Roping",
  "Tennis Elbow",
  "Terry Fox",
  "The Ashes",
  "The Colosseum",
  "The Thunderdome",
  "The Wave",
  "There's No Crying in Baseball",
  "They Have a Deep Bench",
  "Thread the Needle",
  "Throw In the Towel",
  "Tiger Woods",
  "Tony Hawk",
  "Tour de France",
  "Tournament of Roses Parade",
  "Track & Field",
  "Trade Deadline",
  "Transfer Window",
  "Triple Crown",
  "Triple Toe Loop",
  "Tug of War",
  "TV Timeout",
  "Unnecessary Roughness",
  "Unused Gym Membership",
  "Usain Bolt",
  "Venus Williams",
  "Virtue & Moir",
  "Water Polo",
  "Wheelchair Basketball",
  "Whitewater Rafting",
  "Willie Shoemaker",
  "Wimbledon",
  "Win by a Nose",
  "Win by Pin",
  "Win One for the Gipper",
  "World Cup",
  "Wrigley Field",
  "Wrist Brace",
  "Yoga Class",
  "Zamboni",
  "Zombie Nation"
];

words['This & That'] = [
  "3 Yards & A Cloud of Dust",
  "A Lick & A Promise",
  "A Wing & A Prayer",
  "A Wink & A Nod",
  "Adam & Eve",
  "Alaska & Hawaii",
  "All for One & One for All",
  "Ant & Dec",
  "Antony & Cleopatra",
  "Arm & Hammer",
  "Arsenic & Old Lace",
  "Asterix & Obelix",
  "Australia & Oceania",
  "Axis & Allies",
  "Bacon & Eggs",
  "Bagels & Lox",
  "Barnes & Noble",
  "Barnum & Bailey",
  "Bart & Lisa",
  "Batman & Robin",
  "Beauty & The Beast",
  "Bed & Breakfast",
  "Bells & Whistles",
  "Bert & Ernie",
  "Black Hats & Mirrorshades",
  "Block & Tackle",
  "Bonnie & Clyde",
  "Bow & Arrow",
  "Bread & Circuses",
  "Breaking & Entering",
  "Brick & Mortar",
  "Bubble & Squeak",
  "Buddy Holly & The Crickets",
  "Butch & Sundance",
  "Calvin & Hobbes",
  "Cap & Gown",
  "Cat & Mouse",
  "Cease & Desist",
  "Chapter & Verse",
  "Checks & Balances",
  "Chips & Salsa",
  "Chuck Norris",
  "Cloak & Dagger",
  "Coke & Mentos",
  "Command & Conquer",
  "Cops & Robbers",
  "Country & Western",
  "Crash & Burn",
  "Cream & Sugar",
  "Cut & Paste",
  "David & Goliath",
  "Day Late & A Dollar Short",
  "Dr. Jekyll & Mr. Hyde",
  "Dungeons & Dragons",
  "East Is East & West Is West",
  "Eats Shoots & Leaves",
  "Eyes & Ears",
  "Fast & Furious",
  "Field & Stream",
  "Fife & Drum",
  "Fingers & Toes",
  "Fire & Brimstone",
  "Fish & Chips",
  "Flesh & Blood",
  "Flotsam & Jetsam",
  "Footloose & Fancy Free",
  "Forgive & Forget",
  "Fry & Laurie",
  "Fun & Games",
  "Greek & Latin",
  "Grin & Bear It",
  "Guns & Roses",
  "Hack & Slash",
  "Hammer & Sickle",
  "Hand & Glove",
  "Hansel & Gretel",
  "Heart & Soul",
  "Heaven & Earth",
  "Hiccup & Toothless",
  "Hide & Seek",
  "Hit & Miss",
  "Holmes & Watson",
  "Horse & Carriage",
  "Jack & Jill",
  "Jason & The Argonauts",
  "Key & Peele",
  "Knife & Fork",
  "Laurel & Hardy",
  "Law & Order",
  "Lewis & Clark",
  "Life & Limb",
  "Live Long & Prosper",
  "Lock & Key",
  "Lost & Found",
  "Macaroni & Cheese",
  "Mario & Luigi",
  "Milk & Cookies",
  "Mitosis & Meiosis",
  "Mold & Mildew",
  "Mom & Pop",
  "Mortar & Pestle",
  "Mother & Child",
  "Mouse & Keyboard",
  "Mulder & Scully",
  "Newfoundland & Labrador",
  "Nickels & Dimes",
  "Night & Day",
  "Noughts & Crosses",
  "Now & Then",
  "Null & Void",
  "Ones & Zeroes",
  "Orville & Wilbur Wright",
  "Parks & Recreation",
  "Peanut Butter & Jelly",
  "Pen & Ink",
  "Pinky & The Brain",
  "Pins & Needles",
  "Point & Click",
  "Pots & Pans",
  "Pride & Prejudice",
  "Protons & Neutrons",
  "Punch & Judy",
  "Read 'em & Weep",
  "Research & Development",
  "Rest & Recuperate",
  "Rhythm & Blues",
  "Rock & Roll",
  "Rocky & Bullwinkle",
  "Rod & Reel",
  "Rodgers & Hammerstein",
  "Romeo & Juliet",
  "Romulus & Remus",
  "Rosencrantz & Guildenstern",
  "Round & Round",
  "Roy Rogers & Trigger",
  "Salt & Pepper",
  "Samson & Delilah",
  "Savings & Loan",
  "Search & Rescue",
  "Shadow & Bone",
  "Shake & Bake",
  "Shave & A Haircut",
  "Shoes & Socks",
  "Shorts & Hawaiian Shirt",
  "Show & Tell",
  "Shut Up & Dance with Me",
  "Shut Up & Kiss Me",
  "Shut Up & Sit Down",
  "Shut Up & Take My Money",
  "Simon & Garfunkel",
  "Skull & Crossbones",
  "Slip & Slide",
  "Smoke & Mirrors",
  "Smokey & The Bandit",
  "Snakes & Ladders",
  "Snow White & The 7 Dwarfs",
  "Soap & Water",
  "Sonny & Cher",
  "Spaghetti & Meatballs",
  "Spit & Polish",
  "Stand Up & Cheer",
  "Stars & Stripes",
  "Sticks & Stones",
  "Stop & Go",
  "Stumps & Bails",
  "Suit & Tie",
  "Sunshine & Rainbows",
  "Supply & Demand",
  "Swords & Sorcery",
  "Take This Job & Shove It",
  "Tea & Crumpets",
  "The Blind Men & The Elephant",
  "The Cat & The Fiddle",
  "The Old Man & The Sea",
  "The Pit & The Pendulum",
  "The Prince & The Pauper",
  "The Tortoise & The Hare",
  "Thelma & Louise",
  "Thick & Thin",
  "Throw & Catch",
  "Thunder & Lightning",
  "Tigris & Euphrates",
  "To Have & To Hold",
  "Toil & Trouble",
  "Tooth & Nail",
  "Track & Field",
  "Trinidad & Tobago",
  "Tweedledee & Tweedledum",
  "Virtue & Moir",
  "Wailing & Gnashing of Teeth",
  "Wallace & Gromit",
  "War & Peace",
  "Washer & Dryer",
  "Watson & Crick",
  "Wild & Crazy",
  "Wrack & Ruin",
  "Xylem & Phloem",
  "Yin & Yang"
];

words['Top Secret'] = [
  "Adrian Monk",
  "Air Force One",
  "All the King's Men",
  "Arsenic & Old Lace",
  "Baker Street",
  "Base Inside a Volcano",
  "Bermuda Triangle",
  "Bigfoot",
  "Billiard Room",
  "Binoculars",
  "Biological Weapon",
  "Biometric Authentication",
  "Black Hats & Mirrorshades",
  "Blow Up the Bridge",
  "Blue's Clues",
  "Book 'em, Danno",
  "Bootleg Turn",
  "Breaking & Entering",
  "Bring In a Ringer",
  "Brink's Truck",
  "British Nuclear Submarine",
  "Bugged Restaurant",
  "Bulletproof Vest",
  "Car Chase in an Ice Palace",
  "Car Inside a Semi Trailer",
  "Casino Royale",
  "Cat & Mouse",
  "Catch Me If You Can",
  "Charlie's Angels",
  "Chief Ironside",
  "Chuck Norris",
  "Cloak & Dagger",
  "Codenames",
  "Colonel Mustard",
  "Criminal Minds",
  "Crop Circles",
  "Dangling from a Helicopter",
  "Dead Men Don't Wear Plaid",
  "Death Cap Mushroom",
  "Death on the Nile",
  "Decoder Ring",
  "Diabolic Laughter",
  "Diamonds Are Forever",
  "Diplomatic Courier",
  "Disabling the Security Cameras",
  "Do You Expect Me to Talk?",
  "Doctor Watson",
  "Dragnet",
  "Dragon Tattoo",
  "Driving Off a Cliff",
  "Driving Toward a Cliff",
  "Drop In from the Ceiling",
  "Ellery Queen",
  "Encyclopedia Brown",
  "Escape via Hot Air Balloon",
  "Fake Mona Lisa",
  "Fingerprints",
  "Fistfight atop a Moving Train",
  "Fog of War",
  "Following Tracks",
  "For Your Eyes Only",
  "Fort Knox",
  "Glance at the Rearview Mirror",
  "Goldfinger",
  "Goons on Snowmobiles",
  "Grand Theft Auto",
  "Grappling in Zero G",
  "Gun in a Violin Case",
  "Hack into the Mainframe",
  "Hardy Boys",
  "Harry Dresden, Wizard P.I.",
  "Hawaii Five-O",
  "Hide Behind a Lamppost",
  "Hide in a Haystack",
  "Hotel California",
  "Hound of the Baskervilles",
  "I Expect You to Die",
  "Incredibly Lifelike Mask",
  "Inspector Gadget",
  "Intrepid Reporter",
  "Invisible Ink",
  "Jam the Transmission",
  "Just a Normal Kitchen Knife",
  "Kiss Me, Deadly",
  "Knife to a Gun Fight",
  "Knight Rider",
  "Knockout Punch",
  "Lead Pipe",
  "Lie Detector",
  "Magnifying Glass",
  "Marathon Man",
  "Miami Vice",
  "Microfilm",
  "Mike Hammer",
  "Milady de Winter",
  "Miss Moneypenny",
  "Moonraker",
  "Nancy Drew",
  "Nick Fury",
  "Night Vision Goggles",
  "Nikki Heat",
  "North by Northwest",
  "Nuclear Football",
  "Oak Island Mystery",
  "Obvious Password",
  "Ocean's 11",
  "Oil Pipeline Explosion",
  "One Night Ultimate Werewolf",
  "Ordinary-Looking Pen",
  "Ordinary-Looking Umbrella",
  "Orient Express",
  "Painting with the Eyes Cut Out",
  "Parabolic Microphone",
  "Parachute to Safety",
  "Perry the Platypus",
  "Pickpocket",
  "Pink Panther",
  "Piranha Tank",
  "Poker Face",
  "Police Siren",
  "Prisoner Exchange",
  "Professor Moriarty",
  "Q",
  "Quicksand",
  "Really Short Henchman",
  "Really Tall Henchman",
  "Red Herring",
  "Richard Castle",
  "Rolex Submariner Wristwatch",
  "Room Full of Ninjas",
  "Roswell, New Mexico",
  "Russian Missile Base",
  "Safecracker",
  "Scooby-Doo",
  "Scotland Yard",
  "Secret Door",
  "Secret Government Warehouse",
  "Secret Handshake",
  "Shaken, Not Stirred",
  "Sherlock Holmes",
  "Shoe Phone",
  "Shoot Off the Lock",
  "Shoot Out the Tires",
  "Sing Sing",
  "Skyfall",
  "Smoke Screen",
  "Sneakers",
  "Spy Satellite",
  "St. Moritz",
  "Stephanie Plum",
  "Sue Thomas: F.B.Eye",
  "Suitcase Full of Money",
  "Surveillance Van",
  "Swat Team",
  "Swiss Bank Account",
  "Swiss Chalet",
  "Sword Cane",
  "Tail a Suspect",
  "Take Over the World",
  "The Bavarian Illuminati",
  "The Berlin Wall",
  "The Big Sleep",
  "The Butler Did It",
  "The Crown Jewels",
  "The Da Vinci Code",
  "The Day of the Jackal",
  "The Hunt for Red October",
  "The Maltese Falcon",
  "The Manchurian Candidate",
  "The Name of the Rose",
  "The Princes in the Tower",
  "The Secret of the Old Clock",
  "The Shadow",
  "The Spy Who Came In from the Cold",
  "The Spy Who Loved Me",
  "This Tape Will Self-Destruct",
  "Thunderball",
  "Ticking Time Bomb",
  "Tinker Tailor Soldier Spy",
  "Trace the Call",
  "Tranquilizer Dart",
  "Trapped in an Elevator",
  "Trench Coat",
  "Trojan Horse",
  "U-Boat",
  "UFO",
  "Underwater Hideout",
  "Valet Who Knows Kung Fu",
  "Velma's Glasses",
  "Ventilation Duct",
  "Veronica Mars",
  "Villain with a Cat",
  "Voice Modulator",
  "White-Collar Crime",
  "Who Framed Roger Rabbit?",
  "Who Shot J.R.?",
  "Wire Tapping"
];

words['Travel'] = [
  "291 Miles to Wall Drug",
  "5 Euro Banknote",
  "Aloha",
  "Angkor Wat",
  "Arc de Triomphe",
  "Around the World in 80 Days",
  "Backpack Across Europe",
  "Baggage Carousel",
  "Bed & Breakfast",
  "Bedbugs",
  "Bellhop",
  "Beret",
  "Bermuda Triangle",
  "Black Forest",
  "British Pound",
  "Broadway",
  "Bronx Zoo",
  "Buckle Up",
  "Bulgarians Nod to Say No",
  "Bullet Train",
  "Burj Khalifa",
  "Business Class",
  "Call a Tow Truck",
  "Canadian Dollar",
  "Cannonball Run",
  "Cape Horn",
  "Car Camping",
  "Caravan Camel",
  "Carmen Sandiego",
  "Cherry Blossom Festival",
  "Chicago O'Hare",
  "Chichen Itza",
  "Chinese Lion Dance",
  "Christchurch, New Zealand",
  "Chuck Norris",
  "Cloverleaf Interchange",
  "Compass Needle",
  "Cook Islands",
  "Czech Hiking Markers",
  "Dallas",
  "Day at the Beach",
  "Dia de los Muertos",
  "Dining Car",
  "Disneyland",
  "Double-Decker Bus",
  "Down the Rabbit Hole",
  "Dramamine",
  "Drive on the Left",
  "Easter Island",
  "Easy Rider",
  "Edinburgh Castle",
  "Eiffel Tower",
  "Emergency Epinephrine",
  "Empire State Building",
  "Event of a Water Landing",
  "Exit May Be Behind You",
  "Extra Pair of Undies",
  "Faster Than Light",
  "Fez",
  "Finnish Sauna",
  "Flat Tire",
  "Flight Simulator",
  "Florida Keys",
  "Fork in the Road",
  "Frequent Flyer Miles",
  "Gator Wrestler",
  "German Autobahn",
  "Glass-Bottom Boat",
  "Golden Gate Bridge",
  "Gondolier",
  "GPS",
  "Graceland",
  "Grand Ole Opry",
  "Great Wall of China",
  "Hagia Sophia",
  "Heathrow",
  "Hershey, Pennsylvania",
  "Hitchhiker's Guide",
  "Hollywood Boulevard",
  "Horse & Carriage",
  "Hotel Pool",
  "Hotel Shampoo",
  "Incompatible Electric Outlet",
  "Indian Rupee",
  "Irish Pub",
  "Italian Pizza Oven",
  "Ivory Coast",
  "Japanese Tea Ceremony",
  "Jerusalem",
  "Jet Lag",
  "Kabuki Theatre",
  "Kimono",
  "Kingston, Jamaica",
  "Kiss the Blarney Stone",
  "Landing Gear",
  "Lantern Festival",
  "Liverpool",
  "London Eye",
  "London Underground",
  "Machu Picchu",
  "Madagascar",
  "Magic Carpet",
  "Makgadikgadi Salt Pans",
  "Mardi Gras",
  "Mariachi Band",
  "Mecca",
  "Mexican Peso",
  "Middle of Nowhere",
  "Mind the Gap",
  "Monument Valley",
  "Moose Jaw, Saskatchewan",
  "Mount Everest",
  "Mount Fuji",
  "Museum of Science & Industry",
  "National Geographic",
  "Nickels & Dimes",
  "No Place Like Home",
  "Oktoberfest",
  "Orient Express",
  "Pack Llama",
  "Panama Canal",
  "Papers, Please",
  "Parisian Café",
  "Passport",
  "Phoenix, Arizona",
  "Pickpocket",
  "Plate of Enchiladas",
  "Pounding Cassava",
  "Poutine",
  "Prague",
  "Queensland",
  "Rental Car",
  "Rio",
  "Roald Amundsen",
  "Roaming Charges",
  "Rodeo Drive",
  "Roman Aqueducts",
  "Room Service",
  "Route 66",
  "Running of the Bulls",
  "RV Parking",
  "Sacred Cows",
  "Scuba Diving",
  "See the Ice Caves!",
  "Selfie Stick",
  "Shetland Islands",
  "Shorts & Hawaiian Shirt",
  "Ski Lift",
  "Sleep Mask",
  "Sleeper Car",
  "Space Elevator",
  "Space Tourism",
  "St. Elmo's Fire",
  "Standby Passengers",
  "Statue of Christ the Redeemer",
  "Statue of Liberty",
  "Stonehenge",
  "Street Musician",
  "Sturgis Motorcycle Rally",
  "Summer House in Maine",
  "Swiss Chalet",
  "Sydney Opera House",
  "The Chunnel",
  "The Kremlin",
  "The Leaning Tower of Pisa",
  "The Lincoln Memorial",
  "The Louvre Museum",
  "The Odyssey",
  "The Parthenon",
  "The Road Goes Ever On & On",
  "The Space Needle",
  "The Taj Mahal",
  "This Lousy T-Shirt",
  "Thor Heyerdahl",
  "Tomb of the Unknown Soldier",
  "Total Eclipse",
  "Tour Bus",
  "Tour de France",
  "Trained Fugu Chef",
  "Travel Insurance",
  "Travel-Size Toothpaste",
  "Travels with Charley",
  "Tray Table Up",
  "Turkish Coffee",
  "Vatican City",
  "Vegemite Sandwich",
  "Victoria Falls",
  "Washington Monument",
  "Water Slide",
  "Weigh Anchor",
  "Whale Watching",
  "Where the Wild Things Are",
  "White Cliffs of Dover",
  "Working Vacation",
  "World Cup",
  "World's Largest Ball of Twine",
  "Yellowstone National Park",
  "Yelp"
];

words['Video Games'] = [
  "1-Up Mushroom",
  "Achievement Unlocked",
  "All Your Base Are Belong to Us",
  "Angry Birds",
  "Arrow in the Knee",
  "Artemis Bridge Simulator",
  "Assassin's Creed",
  "Asteroids",
  "Baba Is You",
  "Baldur's Gate",
  "Battlefield 3",
  "Beat Saber",
  "Biohazard",
  "Black Mesa",
  "Blizzard Entertainment",
  "Blue Shell",
  "Boom Mania",
  "Borderlands",
  "Boss Fight",
  "Bowser",
  "Bulbasaur",
  "Bullet Time",
  "Button Masher",
  "Call of Duty",
  "Candy Crush",
  "Capture the Flag",
  "Carmen Sandiego",
  "Castle Crashers",
  "CGE",
  "Chaos Emeralds",
  "Charmander",
  "Chuck Norris",
  "Cloud Strife",
  "Codenames",
  "Command & Conquer",
  "Companion Cube",
  "Crash Bandicoot",
  "Creeper",
  "Crossbow",
  "Dagger of Time",
  "Dance Dance Revolution",
  "Dark Souls",
  "Diablo",
  "Diamond Pickaxe",
  "Discord Server",
  "Do a Barrel Roll!",
  "Doki Doki Literature Club!",
  "Don't Shoot Food!",
  "Donkey Kong",
  "Doom",
  "Druidstone",
  "Duke Nukem",
  "Dungeon Keeper",
  "Dust II",
  "Easter Egg",
  "Elden Ring",
  "Elder Scrolls",
  "Epyx Winter Games",
  "Eve Online",
  "Facial Motion Capture",
  "Factorio",
  "Fallout",
  "Fish Fillets",
  "Five Nights at Freddy's",
  "Flight Simulator",
  "Fog of War",
  "Fortnite Battle Bus",
  "Galaxy Trucker",
  "Game Over",
  "Gatling Gun",
  "Grand Theft Auto",
  "Greg the Garlic Farmer",
  "Guitar Hero",
  "Hack & Slash",
  "Half-Life",
  "Hall of Fame",
  "Halo",
  "Headcrab",
  "Health Potion",
  "Hearthstone",
  "Hogwarts Legacy",
  "Horizon",
  "I Expect You to Die",
  "Insert Coin",
  "Iron Golem",
  "Joystick",
  "Jumanji",
  "Katana",
  "Kerbal Space Program",
  "Kingdom Hearts",
  "Lan Party",
  "Lara Croft",
  "Leap of Faith",
  "Leeroy Jenkins",
  "Lemmings",
  "Little Big Planet",
  "Loot Llama",
  "Machinarium",
  "Madden NFL",
  "Mana Crystal",
  "Mario & Luigi",
  "Mario Kart",
  "Medal of Honor",
  "Metal Gear Solid",
  "Minesweeper",
  "Mirror's Edge",
  "Monument Valley",
  "Morrowind",
  "Mount & Blade",
  "Mouse & Keyboard",
  "Murloc",
  "Myst",
  "N00b",
  "Need for Speed",
  "Nerfed",
  "Neverwinter Nights",
  "Nice Day for Fishin', Ain't It?",
  "Nintendo Switch",
  "Ocarina of Time",
  "One More Turn",
  "Oregon Trail",
  "Pac-Man",
  "Papers, Please",
  "Patch",
  "Physics Engine",
  "Pikachu",
  "Pinball",
  "Pixel Art",
  "Pokeball",
  "Pong",
  "Portal Gun",
  "Praise the Sun!",
  "Press F to Pay Respects",
  "Prince of Persia",
  "Princess Peach",
  "Puzzle Pirates",
  "Quake",
  "Queen of Blades",
  "Rage Quit",
  "Ratchet & Clank",
  "Red Dead Redemption",
  "Resident Evil",
  "Rocket Jump",
  "Roller Coaster Tycoon",
  "Sandbox",
  "Scratch Program",
  "Sega Genesis",
  "Shadowrun",
  "Sid Meier",
  "Silent Hill",
  "Sim City",
  "Skill Tree",
  "Skyrim",
  "Solitaire",
  "Sonic the Hedgehog",
  "Space Invaders",
  "Spawn Camper",
  "Splash Damage",
  "Split Screen",
  "Spore",
  "Spyro: Year of the Dragon",
  "Star Fox 64",
  "Stardew Valley",
  "Stealth Mode",
  "Stepmania",
  "Street Fighter",
  "Supply Drop",
  "Tamagotchi",
  "Team Fortress",
  "Tears of the Kingdom",
  "Tetris",
  "The Cake Is a Lie",
  "The Last of Us",
  "The Lords of Midnight",
  "The Secret of Monkey Island",
  "The Witcher",
  "Theme Hospital",
  "Through the Ages",
  "Tom Clancy's Rainbow Six",
  "Tomb Raider",
  "Tony Hawk",
  "Total War",
  "Tower Defense",
  "Treasure Chest",
  "Tron",
  "Turok: Dinosaur Hunter",
  "Turtling",
  "Twilight Princess",
  "Twitch Stream",
  "Viva La Dirt League",
  "VR Headset",
  "Wii Sports",
  "Wingspan",
  "World of Tanks",
  "Wreck-It Ralph",
  "Wumpa Fruit",
  "X-COM: UFO Defense",
  "Zelda's Lullaby",
  "Zerg Rush"
];

words['Core'] = [
  "Ace",
  "Africa",
  "Agent",
  "Air",
  "Alaska",
  "Alien",
  "Alps",
  "Amazon",
  "Ambulance",
  "America",
  "Anchor",
  "Angel",
  "Ant",
  "Antarctica",
  "Anthem",
  "Apple",
  "Apron",
  "Arm",
  "Armor",
  "Army",
  "Ash",
  "Astronaut",
  "Atlantis",
  "Attic",
  "Australia",
  "Avalanche",
  "Axe",
  "Aztec",
  "Baby",
  "Back",
  "Bacon",
  "Ball",
  "Balloon",
  "Banana",
  "Band",
  "Bank",
  "Bar",
  "Barbecue",
  "Bark",
  "Bass",
  "Bat",
  "Bath",
  "Battery",
  "Battle",
  "Battleship",
  "Bay",
  "Beach",
  "Beam",
  "Bean",
  "Bear",
  "Beard",
  "Beat",
  "Bed",
  "Bee",
  "Beer",
  "Beijing",
  "Bell",
  "Belt",
  "Bench",
  "Berlin",
  "Bermuda",
  "Berry",
  "Bicycle",
  "Big Bang",
  "Big Ben",
  "Bikini",
  "Bill",
  "Biscuit",
  "Black Hole",
  "Blacksmith",
  "Blade",
  "Blind",
  "Blizzard",
  "Block",
  "Blues",
  "Board",
  "Boil",
  "Bolt",
  "Bomb",
  "Bond",
  "Bonsai",
  "Book",
  "Boom",
  "Boot",
  "Boss",
  "Bottle",
  "Bow",
  "Bowl",
  "Bowler",
  "Box",
  "Boxer",
  "Brain",
  "Brass",
  "Brazil",
  "Bread",
  "Break",
  "Brick",
  "Bride",
  "Bridge",
  "Brother",
  "Brush",
  "Bubble",
  "Buck",
  "Bucket",
  "Buffalo",
  "Bug",
  "Bugle",
  "Bulb",
  "Bunk",
  "Butter",
  "Butterfly",
  "Button",
  "Cable",
  "Caesar",
  "Cake",
  "Calf",
  "Camp",
  "Canada",
  "Cane",
  "Cap",
  "Capital",
  "Captain",
  "Car",
  "Card",
  "Carrot",
  "Casino",
  "Cast",
  "Castle",
  "Cat",
  "Cave",
  "Cell",
  "Centaur",
  "Center",
  "Chain",
  "Chair",
  "Chalk",
  "Change",
  "Charge",
  "Check",
  "Cheese",
  "Cherry",
  "Chest",
  "Chick",
  "China",
  "Chip",
  "Chocolate",
  "Christmas",
  "Church",
  "Circle",
  "Cleopatra",
  "Cliff",
  "Cloak",
  "Clock",
  "Cloud",
  "Club",
  "Coach",
  "Coast",
  "Code",
  "Coffee",
  "Cold",
  "Collar",
  "Columbus",
  "Comb",
  "Comet",
  "Comic",
  "Compound",
  "Computer",
  "Concert",
  "Conductor",
  "Cone",
  "Contract",
  "Cook",
  "Copper",
  "Cotton",
  "Country",
  "Court",
  "Cover",
  "Cow",
  "Cowboy",
  "Crab",
  "Craft",
  "Crane",
  "Crash",
  "Cricket",
  "Cross",
  "Crow",
  "Crown",
  "Crusader",
  "Crystal",
  "Cuckoo",
  "Curry",
  "Cycle",
  "Czech",
  "Dance",
  "Dash",
  "Date",
  "Day",
  "Death",
  "Deck",
  "Degree",
  "Delta",
  "Dentist",
  "Desk",
  "Diamond",
  "Dice",
  "Dinosaur",
  "Director",
  "Disease",
  "Disk",
  "Doctor",
  "Dog",
  "Doll",
  "Dollar",
  "Door",
  "Draft",
  "Dragon",
  "Drawing",
  "Dream",
  "Dress",
  "Dressing",
  "Drill",
  "Driver",
  "Drone",
  "Drop",
  "Drum",
  "Dryer",
  "Duck",
  "Dust",
  "Dwarf",
  "Eagle",
  "Ear",
  "Earth",
  "Earthquake",
  "Easter",
  "Eden",
  "Egg",
  "Egypt",
  "Einstein",
  "Elephant",
  "Embassy",
  "Engine",
  "England",
  "Europe",
  "Eye",
  "Face",
  "Fair",
  "Fall",
  "Fan",
  "Farm",
  "Fence",
  "Fever",
  "Fiddle",
  "Field",
  "Fighter",
  "Figure",
  "File",
  "Film",
  "Fire",
  "Fish",
  "Flag",
  "Flat",
  "Flood",
  "Floor",
  "Flute",
  "Fly",
  "Foam",
  "Fog",
  "Foot",
  "Force",
  "Forest",
  "Fork",
  "France",
  "Frog",
  "Frost",
  "Fuel",
  "Game",
  "Gangster",
  "Garden",
  "Gas",
  "Gear",
  "Genie",
  "Genius",
  "Germany",
  "Ghost",
  "Giant",
  "Glacier",
  "Glass",
  "Glasses",
  "Glove",
  "Goat",
  "Gold",
  "Goldilocks",
  "Golf",
  "Governor",
  "Grace",
  "Grass",
  "Greece",
  "Green",
  "Greenhouse",
  "Groom",
  "Ground",
  "Guitar",
  "Gum",
  "Gymnast",
  "Hair",
  "Halloween",
  "Ham",
  "Hamburger",
  "Hammer",
  "Hand",
  "Hawaii",
  "Hawk",
  "Head",
  "Heart",
  "Helicopter",
  "Helmet",
  "Hercules",
  "Hide",
  "Himalayas",
  "Hit",
  "Hole",
  "Hollywood",
  "Homer",
  "Honey",
  "Hood",
  "Hook",
  "Horn",
  "Horse",
  "Horseshoe",
  "Hose",
  "Hospital",
  "Hotel",
  "House",
  "Ice",
  "Ice Age",
  "Ice Cream",
  "Iceland",
  "Igloo",
  "India",
  "Ink",
  "Iron",
  "Ivory",
  "Jack",
  "Jail",
  "Jam",
  "Jellyfish",
  "Jet",
  "Jeweler",
  "Joan of Arc",
  "Jockey",
  "Joker",
  "Judge",
  "Jumper",
  "Jupiter",
  "Kangaroo",
  "Ketchup",
  "Key",
  "Kick",
  "Kid",
  "Kilt",
  "King",
  "King Arthur",
  "Kiss",
  "Kitchen",
  "Kiwi",
  "Knife",
  "Knight",
  "Knot",
  "Kung Fu",
  "Lab",
  "Lace",
  "Ladder",
  "Lap",
  "Laser",
  "Laundry",
  "Lawyer",
  "Lead",
  "Leaf",
  "Leather",
  "Lemon",
  "Lemonade",
  "Leprechaun",
  "Letter",
  "Life",
  "Light",
  "Lightning",
  "Limousine",
  "Line",
  "Link",
  "Lion",
  "Lip",
  "Litter",
  "Loch Ness",
  "Lock",
  "Locust",
  "Log",
  "London",
  "Love",
  "Luck",
  "Lumberjack",
  "Lunch",
  "Magazine",
  "Magician",
  "Mail",
  "Makeup",
  "Mammoth",
  "Manicure",
  "Map",
  "Maple",
  "Maracas",
  "Marathon",
  "Marble",
  "March",
  "Mark",
  "Mass",
  "Match",
  "Medic",
  "Memory",
  "Mercury",
  "Mess",
  "Meter",
  "Mexico",
  "Microscope",
  "Microwave",
  "Mile",
  "Milk",
  "Mill",
  "Millionaire",
  "Mine",
  "Minotaur",
  "Mint",
  "Minute",
  "Mirror",
  "Miss",
  "Missile",
  "Model",
  "Mohawk",
  "Mole",
  "Mona Lisa",
  "Monkey",
  "Moon",
  "Moscow",
  "Moses",
  "Mosquito",
  "Mother",
  "Mount",
  "Mountie",
  "Mouse",
  "Mouth",
  "Mud",
  "Mug",
  "Mummy",
  "Musketeer",
  "Mustard",
  "Nail",
  "Napoleon",
  "Needle",
  "Nerve",
  "Net",
  "New York",
  "Newton",
  "Night",
  "Ninja",
  "Noah",
  "Nose",
  "Note",
  "Notre Dame",
  "Novel",
  "Nurse",
  "Nut",
  "Nylon",
  "Oasis",
  "Octopus",
  "Oil",
  "Olive",
  "Olympus",
  "Onion",
  "Opera",
  "Orange",
  "Organ",
  "Pacific",
  "Pad",
  "Paddle",
  "Page",
  "Paint",
  "Palm",
  "Pan",
  "Pants",
  "Paper",
  "Parachute",
  "Parade",
  "Park",
  "Parrot",
  "Part",
  "Pass",
  "Paste",
  "Patient",
  "Pea",
  "Peach",
  "Peanut",
  "Pearl",
  "Pen",
  "Penguin",
  "Penny",
  "Pentagon",
  "Pepper",
  "Pew",
  "Phoenix",
  "Piano",
  "Pie",
  "Pig",
  "Pillow",
  "Pilot",
  "Pin",
  "Pine",
  "Pipe",
  "Pirate",
  "Pistol",
  "Pit",
  "Pitch",
  "Pitcher",
  "Pizza",
  "Plane",
  "Plastic",
  "Plate",
  "Platypus",
  "Play",
  "Plot",
  "Pocket",
  "Point",
  "Poison",
  "Pole",
  "Police",
  "Polish",
  "Polo",
  "Pool",
  "Pop",
  "Popcorn",
  "Port",
  "Post",
  "Potato",
  "Potter",
  "Pound",
  "Powder",
  "Press",
  "Princess",
  "Pumpkin",
  "Pupil",
  "Puppet",
  "Purse",
  "Pyramid",
  "Quack",
  "Quarter",
  "Queen",
  "Rabbit",
  "Racket",
  "Radio",
  "Rail",
  "Rainbow",
  "Ram",
  "Ranch",
  "Rat",
  "Ray",
  "Razor",
  "Record",
  "Reindeer",
  "Revolution",
  "Rice",
  "Rifle",
  "Ring",
  "Rip",
  "River",
  "Road",
  "Robin",
  "Robot",
  "Rock",
  "Rodeo",
  "Roll",
  "Rome",
  "Root",
  "Rope",
  "Rose",
  "Roulette",
  "Round",
  "Row",
  "Rubber",
  "Ruler",
  "Russia",
  "Rust",
  "Sack",
  "Saddle",
  "Sahara",
  "Sail",
  "Salad",
  "Saloon",
  "Salsa",
  "Salt",
  "Sand",
  "Santa",
  "Satellite",
  "Saturn",
  "Saw",
  "Scale",
  "Scarecrow",
  "School",
  "Scientist",
  "Scorpion",
  "Scratch",
  "Screen",
  "Scroll",
  "Scuba Diver",
  "Seal",
  "Second",
  "Server",
  "Shadow",
  "Shakespeare",
  "Shampoo",
  "Shark",
  "Shed",
  "Sheet",
  "Shell",
  "Sherlock",
  "Sherwood",
  "Ship",
  "Shoe",
  "Shoot",
  "Shop",
  "Shorts",
  "Shot",
  "Shoulder",
  "Shower",
  "Sign",
  "Silk",
  "Sink",
  "Sister",
  "Skates",
  "Ski",
  "Skull",
  "Skyscraper",
  "Sled",
  "Sleep",
  "Sling",
  "Slip",
  "Slipper",
  "Sloth",
  "Slug",
  "Smell",
  "Smoke",
  "Smoothie",
  "Smuggler",
  "Snake",
  "Snap",
  "Snow",
  "Snowman",
  "Soap",
  "Sock",
  "Soldier",
  "Soul",
  "Sound",
  "Soup",
  "Space",
  "Spell",
  "Sphinx",
  "Spider",
  "Spike",
  "Spine",
  "Spirit",
  "Spoon",
  "Spot",
  "Spray",
  "Spring",
  "Spurs",
  "Spy",
  "Square",
  "Squash",
  "Squirrel",
  "St. Patrick",
  "Stable",
  "Stadium",
  "Staff",
  "Stamp",
  "Star",
  "State",
  "Steam",
  "Steel",
  "Step",
  "Stethoscope",
  "Stick",
  "Sticker",
  "Stock",
  "Storm",
  "Story",
  "Straw",
  "Stream",
  "Street",
  "Strike",
  "String",
  "Sub",
  "Sugar",
  "Suit",
  "Sumo",
  "Sun",
  "Superhero",
  "Swamp",
  "Sweat",
  "Swing",
  "Switch",
  "Sword",
  "Table",
  "Tablet",
  "Tag",
  "Tail",
  "Tank",
  "Tap",
  "Taste",
  "Tattoo",
  "Tea",
  "Teacher",
  "Team",
  "Tear",
  "Telescope",
  "Temple",
  "Texas",
  "Theater",
  "Thief",
  "Thumb",
  "Thunder",
  "Tick",
  "Tie",
  "Tiger",
  "Time",
  "Tin",
  "Tip",
  "Tipi",
  "Toast",
  "Tokyo",
  "Tooth",
  "Torch",
  "Tornado",
  "Tower",
  "Track",
  "Train",
  "Triangle",
  "Trick",
  "Trip",
  "Troll",
  "Trunk",
  "Tube",
  "Tunnel",
  "Turkey",
  "Turtle",
  "Tutu",
  "Tuxedo",
  "Undertaker",
  "Unicorn",
  "University",
  "Vacuum",
  "Valentine",
  "Vampire",
  "Van",
  "Venus",
  "Vet",
  "Viking",
  "Violet",
  "Virus",
  "Volcano",
  "Volume",
  "Wagon",
  "Waitress",
  "Wake",
  "Wall",
  "Walrus",
  "War",
  "Washer",
  "Washington",
  "Watch",
  "Water",
  "Wave",
  "Web",
  "Wedding",
  "Well",
  "Werewolf",
  "Whale",
  "Wheel",
  "Wheelchair",
  "Whip",
  "Whistle",
  "Wind",
  "Window",
  "Wing",
  "Wish",
  "Witch",
  "Wizard",
  "Wonderland",
  "Wood",
  "Wool",
  "Worm",
  "Yard",
  "Yellowstone",
  "Zombie"
];

const gameTypes = Object.keys(words);

async function fetchCustomWords(category, apiKey) {
  const groq = new Groq({
    apiKey,
    dangerouslyAllowBrowser: true
  });

  const query = getQuery(category);
  const messages = [
    {
      role: 'user',
      content: query
    }
  ]
  const response = await groq.chat.completions.create({
    messages,
    model: 'llama3-8b-8192',
    temperature: 1,
    max_tokens: 1024,
    top_p: 1,
    stream: false,
    stop: null,
    response_format: {
      "type": "json_object"
    }
  });

  let words = JSON.parse(response.choices[0].message.content);

  if(typeof words !== 'object' || !Array.isArray(words?.words)) {
    throw new Error('Invalid response from API');
  }

  //Capitalize the first letter of each word
  return words.words.map(
    word => word
      .split(/(?=[A-Z])/)
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ')
  );
}

async function* wordGenerator(gameType = 'Standard', customCategory = 'dog', apiKey = '') {
  let typeWords;
  switch(gameType) {
    case 'Custom':
      if (customCategory && apiKey) {
        words = await fetchCustomWords(customCategory, apiKey);
      } else {
        words = [];
      }
      break;
    default:
      typeWords = Object.assign([], words[gameType]);
      break;
  }

  while(true) {
    if(typeWords.length > 0) {
      const RAND_INDEX = Math.floor(Math.random() * typeWords.length);
      const RAND_WORD = typeWords[RAND_INDEX];
      typeWords.splice(RAND_INDEX, 1);
      yield RAND_WORD;
    } else {
      yield '';
    }
  }
}

export { gameTypes, wordGenerator };